/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_bicycle_model_reverse_expl_ode_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[30] = {10, 3, 0, 8, 16, 24, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 8, 0, 1, 2, 3, 4, 5, 6, 9};
static const casadi_int casadi_s1[37] = {3, 10, 0, 3, 6, 9, 12, 15, 18, 21, 22, 23, 24, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s2[107] = {10, 10, 0, 10, 20, 30, 40, 50, 60, 70, 78, 86, 94, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 8, 0, 1, 2, 3, 4, 5, 6, 9};
static const casadi_int casadi_s3[113] = {10, 10, 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s4[43] = {10, 10, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 2, 3, 6, 2, 3, 6, 2, 3, 6, 2, 3, 6, 2, 3, 6, 2, 3, 6, 2, 3, 6, 2, 3, 6, 2, 3, 6, 2, 3, 6};
static const casadi_int casadi_s5[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s6[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s7[27] = {7, 3, 0, 7, 14, 21, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s8[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s9[3] = {0, 0, 0};
static const casadi_int casadi_s10[11] = {10, 1, 0, 7, 2, 3, 5, 6, 7, 8, 9};
static const casadi_int casadi_s11[59] = {55, 1, 0, 55, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54};

static const casadi_real casadi_c0[24] = {0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.};

/* f1tenth_bicycle_model_reverse_expl_ode_hess:(i0[7],i1[7x7],i2[7x3],i3[7],i4[3],i5[])->(o0[10x1,7nz],o1[55]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, *w3=w+13, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, *w19=w+35, *w20=w+135, *w21=w+184, *w22=w+205, *w23=w+275, *w24=w+345, *w25=w+369, *w26=w+393, *w29=w+487, *w30=w+581, *w31=w+591, *w32=w+601, *w33=w+611, *w34=w+621, *w35=w+631, *w36=w+641, *w37=w+651, *w38=w+659, *w39=w+667, w40, w41, w42, w43, w44, *w50=w+680, w51, *w52=w+684, *w53=w+687, *w54=w+690, *w55=w+693, *w56=w+696, *w57=w+699, *w58=w+702, *w59=w+705, *w60=w+708, *w61=w+711;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = input[3][0] */
  casadi_copy(arg[3], 7, w3);
  /* #4: {@4, @5, @6, @7, @8, @9, @10} = vertsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  w8 = w3[4];
  w9 = w3[5];
  w10 = w3[6];
  /* #5: @11 = (@2*@5) */
  w11  = (w2*w5);
  /* #6: @12 = (@1*@11) */
  w12  = (w1*w11);
  /* #7: @13 = sin(@0) */
  w13 = sin( w0 );
  /* #8: @14 = (@2*@4) */
  w14  = (w2*w4);
  /* #9: @15 = (@13*@14) */
  w15  = (w13*w14);
  /* #10: @12 = (@12-@15) */
  w12 -= w15;
  /* #11: output[0][0] = @12 */
  if (res[0]) res[0][0] = w12;
  /* #12: @12 = 3.02115 */
  w12 = 3.0211480362537761e+00;
  /* #13: @15 = input[0][6] */
  w15 = arg[0] ? arg[0][6] : 0;
  /* #14: @16 = tan(@15) */
  w16 = tan( w15 );
  /* #15: @16 = (@16*@6) */
  w16 *= w6;
  /* #16: @16 = (@12*@16) */
  w16  = (w12*w16);
  /* #17: @17 = 3.012 */
  w17 = 3.0120000000000000e+00;
  /* #18: @18 = 0.675676 */
  w18 = 6.7567567567567566e-01;
  /* #19: @18 = (@18*@7) */
  w18 *= w7;
  /* #20: @17 = (@17*@18) */
  w17 *= w18;
  /* #21: @16 = (@16-@17) */
  w16 -= w17;
  /* #22: @17 = sin(@0) */
  w17 = sin( w0 );
  /* #23: @17 = (@17*@5) */
  w17 *= w5;
  /* #24: @16 = (@16+@17) */
  w16 += w17;
  /* #25: @17 = cos(@0) */
  w17 = cos( w0 );
  /* #26: @17 = (@17*@4) */
  w17 *= w4;
  /* #27: @16 = (@16+@17) */
  w16 += w17;
  /* #28: output[0][1] = @16 */
  if (res[0]) res[0][1] = w16;
  /* #29: @16 = 61.4282 */
  w16 = 6.1428199999999997e+01;
  /* #30: @16 = (@16*@18) */
  w16 *= w18;
  /* #31: output[0][2] = @16 */
  if (res[0]) res[0][2] = w16;
  /* #32: @16 = 0.331 */
  w16 = 3.3100000000000002e-01;
  /* #33: @2 = (@2/@16) */
  w2 /= w16;
  /* #34: @2 = (@2*@6) */
  w2 *= w6;
  /* #35: @16 = cos(@15) */
  w16 = cos( w15 );
  /* #36: @18 = sq(@16) */
  w18 = casadi_sq( w16 );
  /* #37: @2 = (@2/@18) */
  w2 /= w18;
  /* #38: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #39: output[0][4] = @8 */
  if (res[0]) res[0][4] = w8;
  /* #40: output[0][5] = @9 */
  if (res[0]) res[0][5] = w9;
  /* #41: output[0][6] = @10 */
  if (res[0]) res[0][6] = w10;
  /* #42: @19 = zeros(10x10) */
  casadi_clear(w19, 100);
  /* #43: @20 = input[1][0] */
  casadi_copy(arg[1], 49, w20);
  /* #44: @21 = input[2][0] */
  casadi_copy(arg[2], 21, w21);
  /* #45: @22 = horzcat(@20, @21) */
  rr=w22;
  for (i=0, cs=w20; i<49; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<21; ++i) *rr++ = *cs++;
  /* #46: @23 = @22' */
  for (i=0, rr=w23, cs=w22; i<10; ++i) for (j=0; j<7; ++j) rr[i+j*10] = *cs++;
  /* #47: @24 = 
  [[0, 0, 0, 0, 0, 0, 0, 1, 00, 00], 
   [0, 0, 0, 0, 0, 0, 0, 00, 1, 00], 
   [0, 0, 0, 0, 0, 0, 0, 00, 00, 1]] */
  casadi_copy(casadi_c0, 24, w24);
  /* #48: @25 = @24' */
  casadi_trans(w24,casadi_s1, w25, casadi_s0, iw);
  /* #49: @26 = horzcat(@23, @25) */
  rr=w26;
  for (i=0, cs=w23; i<70; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<24; ++i) *rr++ = *cs++;
  /* #50: @27 = 00 */
  /* #51: @28 = 00 */
  /* #52: @29 = @26' */
  casadi_trans(w26,casadi_s2, w29, casadi_s2, iw);
  /* #53: {@30, @31, @32, @33, @34, @35, @36, @37, @38, @39} = horzsplit(@29) */
  casadi_copy(w29, 10, w30);
  casadi_copy(w29+10, 10, w31);
  casadi_copy(w29+20, 10, w32);
  casadi_copy(w29+30, 10, w33);
  casadi_copy(w29+40, 10, w34);
  casadi_copy(w29+50, 10, w35);
  casadi_copy(w29+60, 10, w36);
  casadi_copy(w29+70, 8, w37);
  casadi_copy(w29+78, 8, w38);
  casadi_copy(w29+86, 8, w39);
  /* #54: {NULL, NULL, @10, @9, NULL, NULL, @8, NULL, NULL, NULL} = vertsplit(@30) */
  w10 = w30[2];
  w9 = w30[3];
  w8 = w30[6];
  /* #55: @17 = (@5*@9) */
  w17  = (w5*w9);
  /* #56: @17 = (@1*@17) */
  w17  = (w1*w17);
  /* #57: @7 = sin(@0) */
  w7 = sin( w0 );
  /* #58: @40 = (@7*@10) */
  w40  = (w7*w10);
  /* #59: @40 = (@11*@40) */
  w40  = (w11*w40);
  /* #60: @17 = (@17-@40) */
  w17 -= w40;
  /* #61: @40 = cos(@0) */
  w40 = cos( w0 );
  /* #62: @41 = (@40*@10) */
  w41  = (w40*w10);
  /* #63: @41 = (@14*@41) */
  w41  = (w14*w41);
  /* #64: @42 = (@4*@9) */
  w42  = (w4*w9);
  /* #65: @42 = (@13*@42) */
  w42  = (w13*w42);
  /* #66: @41 = (@41+@42) */
  w41 += w42;
  /* #67: @17 = (@17-@41) */
  w17 -= w41;
  /* #68: @41 = cos(@15) */
  w41 = cos( w15 );
  /* #69: @41 = sq(@41) */
  w41 = casadi_sq( w41 );
  /* #70: @42 = (@8/@41) */
  w42  = (w8/w41);
  /* #71: @42 = (@6*@42) */
  w42  = (w6*w42);
  /* #72: @42 = (@12*@42) */
  w42  = (w12*w42);
  /* #73: @43 = cos(@0) */
  w43 = cos( w0 );
  /* #74: @44 = (@43*@10) */
  w44  = (w43*w10);
  /* #75: @44 = (@5*@44) */
  w44  = (w5*w44);
  /* #76: @42 = (@42+@44) */
  w42 += w44;
  /* #77: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #78: @10 = (@0*@10) */
  w10  = (w0*w10);
  /* #79: @10 = (@4*@10) */
  w10  = (w4*w10);
  /* #80: @42 = (@42-@10) */
  w42 -= w10;
  /* #81: @45 = 00 */
  /* #82: @46 = 00 */
  /* #83: @10 = 3.02115 */
  w10 = 3.0211480362537761e+00;
  /* #84: @9 = (@10*@9) */
  w9  = (w10*w9);
  /* #85: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #86: @9 = (@9/@18) */
  w9 /= w18;
  /* #87: @2 = (@2/@18) */
  w2 /= w18;
  /* #88: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #89: @15 = sin(@15) */
  w15 = sin( w15 );
  /* #90: @8 = (@15*@8) */
  w8  = (w15*w8);
  /* #91: @8 = (@16*@8) */
  w8  = (w16*w8);
  /* #92: @8 = (@2*@8) */
  w8  = (w2*w8);
  /* #93: @9 = (@9+@8) */
  w9 += w8;
  /* #94: @47 = 00 */
  /* #95: @48 = 00 */
  /* #96: @49 = 00 */
  /* #97: @50 = vertcat(@27, @28, @17, @42, @45, @46, @9, @47, @48, @49) */
  rr=w50;
  *rr++ = w17;
  *rr++ = w42;
  *rr++ = w9;
  /* #98: {NULL, NULL, @17, @42, NULL, NULL, @9, NULL, NULL, NULL} = vertsplit(@31) */
  w17 = w31[2];
  w42 = w31[3];
  w9 = w31[6];
  /* #99: @8 = (@5*@42) */
  w8  = (w5*w42);
  /* #100: @8 = (@1*@8) */
  w8  = (w1*w8);
  /* #101: @44 = (@7*@17) */
  w44  = (w7*w17);
  /* #102: @44 = (@11*@44) */
  w44  = (w11*w44);
  /* #103: @8 = (@8-@44) */
  w8 -= w44;
  /* #104: @44 = (@40*@17) */
  w44  = (w40*w17);
  /* #105: @44 = (@14*@44) */
  w44  = (w14*w44);
  /* #106: @51 = (@4*@42) */
  w51  = (w4*w42);
  /* #107: @51 = (@13*@51) */
  w51  = (w13*w51);
  /* #108: @44 = (@44+@51) */
  w44 += w51;
  /* #109: @8 = (@8-@44) */
  w8 -= w44;
  /* #110: @44 = (@9/@41) */
  w44  = (w9/w41);
  /* #111: @44 = (@6*@44) */
  w44  = (w6*w44);
  /* #112: @44 = (@12*@44) */
  w44  = (w12*w44);
  /* #113: @51 = (@43*@17) */
  w51  = (w43*w17);
  /* #114: @51 = (@5*@51) */
  w51  = (w5*w51);
  /* #115: @44 = (@44+@51) */
  w44 += w51;
  /* #116: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #117: @17 = (@4*@17) */
  w17  = (w4*w17);
  /* #118: @44 = (@44-@17) */
  w44 -= w17;
  /* #119: @46 = 00 */
  /* #120: @42 = (@10*@42) */
  w42  = (w10*w42);
  /* #121: @42 = (@6*@42) */
  w42  = (w6*w42);
  /* #122: @42 = (@42/@18) */
  w42 /= w18;
  /* #123: @9 = (@15*@9) */
  w9  = (w15*w9);
  /* #124: @9 = (@16*@9) */
  w9  = (w16*w9);
  /* #125: @9 = (@2*@9) */
  w9  = (w2*w9);
  /* #126: @42 = (@42+@9) */
  w42 += w9;
  /* #127: @47 = 00 */
  /* #128: @48 = 00 */
  /* #129: @49 = 00 */
  /* #130: @52 = vertcat(@27, @28, @8, @44, @45, @46, @42, @47, @48, @49) */
  rr=w52;
  *rr++ = w8;
  *rr++ = w44;
  *rr++ = w42;
  /* #131: {NULL, NULL, @8, @44, NULL, NULL, @42, NULL, NULL, NULL} = vertsplit(@32) */
  w8 = w32[2];
  w44 = w32[3];
  w42 = w32[6];
  /* #132: @9 = (@5*@44) */
  w9  = (w5*w44);
  /* #133: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #134: @17 = (@7*@8) */
  w17  = (w7*w8);
  /* #135: @17 = (@11*@17) */
  w17  = (w11*w17);
  /* #136: @9 = (@9-@17) */
  w9 -= w17;
  /* #137: @17 = (@40*@8) */
  w17  = (w40*w8);
  /* #138: @17 = (@14*@17) */
  w17  = (w14*w17);
  /* #139: @51 = (@4*@44) */
  w51  = (w4*w44);
  /* #140: @51 = (@13*@51) */
  w51  = (w13*w51);
  /* #141: @17 = (@17+@51) */
  w17 += w51;
  /* #142: @9 = (@9-@17) */
  w9 -= w17;
  /* #143: @17 = (@42/@41) */
  w17  = (w42/w41);
  /* #144: @17 = (@6*@17) */
  w17  = (w6*w17);
  /* #145: @17 = (@12*@17) */
  w17  = (w12*w17);
  /* #146: @51 = (@43*@8) */
  w51  = (w43*w8);
  /* #147: @51 = (@5*@51) */
  w51  = (w5*w51);
  /* #148: @17 = (@17+@51) */
  w17 += w51;
  /* #149: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #150: @8 = (@4*@8) */
  w8  = (w4*w8);
  /* #151: @17 = (@17-@8) */
  w17 -= w8;
  /* #152: @46 = 00 */
  /* #153: @44 = (@10*@44) */
  w44  = (w10*w44);
  /* #154: @44 = (@6*@44) */
  w44  = (w6*w44);
  /* #155: @44 = (@44/@18) */
  w44 /= w18;
  /* #156: @42 = (@15*@42) */
  w42  = (w15*w42);
  /* #157: @42 = (@16*@42) */
  w42  = (w16*w42);
  /* #158: @42 = (@2*@42) */
  w42  = (w2*w42);
  /* #159: @44 = (@44+@42) */
  w44 += w42;
  /* #160: @47 = 00 */
  /* #161: @48 = 00 */
  /* #162: @49 = 00 */
  /* #163: @53 = vertcat(@27, @28, @9, @17, @45, @46, @44, @47, @48, @49) */
  rr=w53;
  *rr++ = w9;
  *rr++ = w17;
  *rr++ = w44;
  /* #164: {NULL, NULL, @9, @17, NULL, NULL, @44, NULL, NULL, NULL} = vertsplit(@33) */
  w9 = w33[2];
  w17 = w33[3];
  w44 = w33[6];
  /* #165: @42 = (@5*@17) */
  w42  = (w5*w17);
  /* #166: @42 = (@1*@42) */
  w42  = (w1*w42);
  /* #167: @8 = (@7*@9) */
  w8  = (w7*w9);
  /* #168: @8 = (@11*@8) */
  w8  = (w11*w8);
  /* #169: @42 = (@42-@8) */
  w42 -= w8;
  /* #170: @8 = (@40*@9) */
  w8  = (w40*w9);
  /* #171: @8 = (@14*@8) */
  w8  = (w14*w8);
  /* #172: @51 = (@4*@17) */
  w51  = (w4*w17);
  /* #173: @51 = (@13*@51) */
  w51  = (w13*w51);
  /* #174: @8 = (@8+@51) */
  w8 += w51;
  /* #175: @42 = (@42-@8) */
  w42 -= w8;
  /* #176: @8 = (@44/@41) */
  w8  = (w44/w41);
  /* #177: @8 = (@6*@8) */
  w8  = (w6*w8);
  /* #178: @8 = (@12*@8) */
  w8  = (w12*w8);
  /* #179: @51 = (@43*@9) */
  w51  = (w43*w9);
  /* #180: @51 = (@5*@51) */
  w51  = (w5*w51);
  /* #181: @8 = (@8+@51) */
  w8 += w51;
  /* #182: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #183: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #184: @8 = (@8-@9) */
  w8 -= w9;
  /* #185: @46 = 00 */
  /* #186: @17 = (@10*@17) */
  w17  = (w10*w17);
  /* #187: @17 = (@6*@17) */
  w17  = (w6*w17);
  /* #188: @17 = (@17/@18) */
  w17 /= w18;
  /* #189: @44 = (@15*@44) */
  w44  = (w15*w44);
  /* #190: @44 = (@16*@44) */
  w44  = (w16*w44);
  /* #191: @44 = (@2*@44) */
  w44  = (w2*w44);
  /* #192: @17 = (@17+@44) */
  w17 += w44;
  /* #193: @47 = 00 */
  /* #194: @48 = 00 */
  /* #195: @49 = 00 */
  /* #196: @54 = vertcat(@27, @28, @42, @8, @45, @46, @17, @47, @48, @49) */
  rr=w54;
  *rr++ = w42;
  *rr++ = w8;
  *rr++ = w17;
  /* #197: {NULL, NULL, @42, @8, NULL, NULL, @17, NULL, NULL, NULL} = vertsplit(@34) */
  w42 = w34[2];
  w8 = w34[3];
  w17 = w34[6];
  /* #198: @44 = (@5*@8) */
  w44  = (w5*w8);
  /* #199: @44 = (@1*@44) */
  w44  = (w1*w44);
  /* #200: @9 = (@7*@42) */
  w9  = (w7*w42);
  /* #201: @9 = (@11*@9) */
  w9  = (w11*w9);
  /* #202: @44 = (@44-@9) */
  w44 -= w9;
  /* #203: @9 = (@40*@42) */
  w9  = (w40*w42);
  /* #204: @9 = (@14*@9) */
  w9  = (w14*w9);
  /* #205: @51 = (@4*@8) */
  w51  = (w4*w8);
  /* #206: @51 = (@13*@51) */
  w51  = (w13*w51);
  /* #207: @9 = (@9+@51) */
  w9 += w51;
  /* #208: @44 = (@44-@9) */
  w44 -= w9;
  /* #209: @9 = (@17/@41) */
  w9  = (w17/w41);
  /* #210: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #211: @9 = (@12*@9) */
  w9  = (w12*w9);
  /* #212: @51 = (@43*@42) */
  w51  = (w43*w42);
  /* #213: @51 = (@5*@51) */
  w51  = (w5*w51);
  /* #214: @9 = (@9+@51) */
  w9 += w51;
  /* #215: @42 = (@0*@42) */
  w42  = (w0*w42);
  /* #216: @42 = (@4*@42) */
  w42  = (w4*w42);
  /* #217: @9 = (@9-@42) */
  w9 -= w42;
  /* #218: @46 = 00 */
  /* #219: @8 = (@10*@8) */
  w8  = (w10*w8);
  /* #220: @8 = (@6*@8) */
  w8  = (w6*w8);
  /* #221: @8 = (@8/@18) */
  w8 /= w18;
  /* #222: @17 = (@15*@17) */
  w17  = (w15*w17);
  /* #223: @17 = (@16*@17) */
  w17  = (w16*w17);
  /* #224: @17 = (@2*@17) */
  w17  = (w2*w17);
  /* #225: @8 = (@8+@17) */
  w8 += w17;
  /* #226: @47 = 00 */
  /* #227: @48 = 00 */
  /* #228: @49 = 00 */
  /* #229: @55 = vertcat(@27, @28, @44, @9, @45, @46, @8, @47, @48, @49) */
  rr=w55;
  *rr++ = w44;
  *rr++ = w9;
  *rr++ = w8;
  /* #230: {NULL, NULL, @44, @9, NULL, NULL, @8, NULL, NULL, NULL} = vertsplit(@35) */
  w44 = w35[2];
  w9 = w35[3];
  w8 = w35[6];
  /* #231: @17 = (@5*@9) */
  w17  = (w5*w9);
  /* #232: @17 = (@1*@17) */
  w17  = (w1*w17);
  /* #233: @42 = (@7*@44) */
  w42  = (w7*w44);
  /* #234: @42 = (@11*@42) */
  w42  = (w11*w42);
  /* #235: @17 = (@17-@42) */
  w17 -= w42;
  /* #236: @42 = (@40*@44) */
  w42  = (w40*w44);
  /* #237: @42 = (@14*@42) */
  w42  = (w14*w42);
  /* #238: @51 = (@4*@9) */
  w51  = (w4*w9);
  /* #239: @51 = (@13*@51) */
  w51  = (w13*w51);
  /* #240: @42 = (@42+@51) */
  w42 += w51;
  /* #241: @17 = (@17-@42) */
  w17 -= w42;
  /* #242: @42 = (@8/@41) */
  w42  = (w8/w41);
  /* #243: @42 = (@6*@42) */
  w42  = (w6*w42);
  /* #244: @42 = (@12*@42) */
  w42  = (w12*w42);
  /* #245: @51 = (@43*@44) */
  w51  = (w43*w44);
  /* #246: @51 = (@5*@51) */
  w51  = (w5*w51);
  /* #247: @42 = (@42+@51) */
  w42 += w51;
  /* #248: @44 = (@0*@44) */
  w44  = (w0*w44);
  /* #249: @44 = (@4*@44) */
  w44  = (w4*w44);
  /* #250: @42 = (@42-@44) */
  w42 -= w44;
  /* #251: @46 = 00 */
  /* #252: @9 = (@10*@9) */
  w9  = (w10*w9);
  /* #253: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #254: @9 = (@9/@18) */
  w9 /= w18;
  /* #255: @8 = (@15*@8) */
  w8  = (w15*w8);
  /* #256: @8 = (@16*@8) */
  w8  = (w16*w8);
  /* #257: @8 = (@2*@8) */
  w8  = (w2*w8);
  /* #258: @9 = (@9+@8) */
  w9 += w8;
  /* #259: @47 = 00 */
  /* #260: @48 = 00 */
  /* #261: @49 = 00 */
  /* #262: @56 = vertcat(@27, @28, @17, @42, @45, @46, @9, @47, @48, @49) */
  rr=w56;
  *rr++ = w17;
  *rr++ = w42;
  *rr++ = w9;
  /* #263: {NULL, NULL, @17, @42, NULL, NULL, @9, NULL, NULL, NULL} = vertsplit(@36) */
  w17 = w36[2];
  w42 = w36[3];
  w9 = w36[6];
  /* #264: @8 = (@5*@42) */
  w8  = (w5*w42);
  /* #265: @8 = (@1*@8) */
  w8  = (w1*w8);
  /* #266: @44 = (@7*@17) */
  w44  = (w7*w17);
  /* #267: @44 = (@11*@44) */
  w44  = (w11*w44);
  /* #268: @8 = (@8-@44) */
  w8 -= w44;
  /* #269: @44 = (@40*@17) */
  w44  = (w40*w17);
  /* #270: @44 = (@14*@44) */
  w44  = (w14*w44);
  /* #271: @51 = (@4*@42) */
  w51  = (w4*w42);
  /* #272: @51 = (@13*@51) */
  w51  = (w13*w51);
  /* #273: @44 = (@44+@51) */
  w44 += w51;
  /* #274: @8 = (@8-@44) */
  w8 -= w44;
  /* #275: @44 = (@9/@41) */
  w44  = (w9/w41);
  /* #276: @44 = (@6*@44) */
  w44  = (w6*w44);
  /* #277: @44 = (@12*@44) */
  w44  = (w12*w44);
  /* #278: @51 = (@43*@17) */
  w51  = (w43*w17);
  /* #279: @51 = (@5*@51) */
  w51  = (w5*w51);
  /* #280: @44 = (@44+@51) */
  w44 += w51;
  /* #281: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #282: @17 = (@4*@17) */
  w17  = (w4*w17);
  /* #283: @44 = (@44-@17) */
  w44 -= w17;
  /* #284: @46 = 00 */
  /* #285: @42 = (@10*@42) */
  w42  = (w10*w42);
  /* #286: @42 = (@6*@42) */
  w42  = (w6*w42);
  /* #287: @42 = (@42/@18) */
  w42 /= w18;
  /* #288: @9 = (@15*@9) */
  w9  = (w15*w9);
  /* #289: @9 = (@16*@9) */
  w9  = (w16*w9);
  /* #290: @9 = (@2*@9) */
  w9  = (w2*w9);
  /* #291: @42 = (@42+@9) */
  w42 += w9;
  /* #292: @47 = 00 */
  /* #293: @48 = 00 */
  /* #294: @49 = 00 */
  /* #295: @57 = vertcat(@27, @28, @8, @44, @45, @46, @42, @47, @48, @49) */
  rr=w57;
  *rr++ = w8;
  *rr++ = w44;
  *rr++ = w42;
  /* #296: {NULL, NULL, @8, @44, NULL, NULL, @42, NULL, NULL, NULL} = vertsplit(@37) */
  w8 = w37[2];
  w44 = w37[3];
  w42 = w37[6];
  /* #297: @9 = (@5*@44) */
  w9  = (w5*w44);
  /* #298: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #299: @17 = (@7*@8) */
  w17  = (w7*w8);
  /* #300: @17 = (@11*@17) */
  w17  = (w11*w17);
  /* #301: @9 = (@9-@17) */
  w9 -= w17;
  /* #302: @17 = (@40*@8) */
  w17  = (w40*w8);
  /* #303: @17 = (@14*@17) */
  w17  = (w14*w17);
  /* #304: @51 = (@4*@44) */
  w51  = (w4*w44);
  /* #305: @51 = (@13*@51) */
  w51  = (w13*w51);
  /* #306: @17 = (@17+@51) */
  w17 += w51;
  /* #307: @9 = (@9-@17) */
  w9 -= w17;
  /* #308: @17 = (@42/@41) */
  w17  = (w42/w41);
  /* #309: @17 = (@6*@17) */
  w17  = (w6*w17);
  /* #310: @17 = (@12*@17) */
  w17  = (w12*w17);
  /* #311: @51 = (@43*@8) */
  w51  = (w43*w8);
  /* #312: @51 = (@5*@51) */
  w51  = (w5*w51);
  /* #313: @17 = (@17+@51) */
  w17 += w51;
  /* #314: @8 = (@0*@8) */
  w8  = (w0*w8);
  /* #315: @8 = (@4*@8) */
  w8  = (w4*w8);
  /* #316: @17 = (@17-@8) */
  w17 -= w8;
  /* #317: @46 = 00 */
  /* #318: @44 = (@10*@44) */
  w44  = (w10*w44);
  /* #319: @44 = (@6*@44) */
  w44  = (w6*w44);
  /* #320: @44 = (@44/@18) */
  w44 /= w18;
  /* #321: @42 = (@15*@42) */
  w42  = (w15*w42);
  /* #322: @42 = (@16*@42) */
  w42  = (w16*w42);
  /* #323: @42 = (@2*@42) */
  w42  = (w2*w42);
  /* #324: @44 = (@44+@42) */
  w44 += w42;
  /* #325: @47 = 00 */
  /* #326: @48 = 00 */
  /* #327: @49 = 00 */
  /* #328: @58 = vertcat(@27, @28, @9, @17, @45, @46, @44, @47, @48, @49) */
  rr=w58;
  *rr++ = w9;
  *rr++ = w17;
  *rr++ = w44;
  /* #329: {NULL, NULL, @9, @17, NULL, NULL, @44, NULL, NULL, NULL} = vertsplit(@38) */
  w9 = w38[2];
  w17 = w38[3];
  w44 = w38[6];
  /* #330: @42 = (@5*@17) */
  w42  = (w5*w17);
  /* #331: @42 = (@1*@42) */
  w42  = (w1*w42);
  /* #332: @8 = (@7*@9) */
  w8  = (w7*w9);
  /* #333: @8 = (@11*@8) */
  w8  = (w11*w8);
  /* #334: @42 = (@42-@8) */
  w42 -= w8;
  /* #335: @8 = (@40*@9) */
  w8  = (w40*w9);
  /* #336: @8 = (@14*@8) */
  w8  = (w14*w8);
  /* #337: @51 = (@4*@17) */
  w51  = (w4*w17);
  /* #338: @51 = (@13*@51) */
  w51  = (w13*w51);
  /* #339: @8 = (@8+@51) */
  w8 += w51;
  /* #340: @42 = (@42-@8) */
  w42 -= w8;
  /* #341: @8 = (@44/@41) */
  w8  = (w44/w41);
  /* #342: @8 = (@6*@8) */
  w8  = (w6*w8);
  /* #343: @8 = (@12*@8) */
  w8  = (w12*w8);
  /* #344: @51 = (@43*@9) */
  w51  = (w43*w9);
  /* #345: @51 = (@5*@51) */
  w51  = (w5*w51);
  /* #346: @8 = (@8+@51) */
  w8 += w51;
  /* #347: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #348: @9 = (@4*@9) */
  w9  = (w4*w9);
  /* #349: @8 = (@8-@9) */
  w8 -= w9;
  /* #350: @46 = 00 */
  /* #351: @17 = (@10*@17) */
  w17  = (w10*w17);
  /* #352: @17 = (@6*@17) */
  w17  = (w6*w17);
  /* #353: @17 = (@17/@18) */
  w17 /= w18;
  /* #354: @44 = (@15*@44) */
  w44  = (w15*w44);
  /* #355: @44 = (@16*@44) */
  w44  = (w16*w44);
  /* #356: @44 = (@2*@44) */
  w44  = (w2*w44);
  /* #357: @17 = (@17+@44) */
  w17 += w44;
  /* #358: @47 = 00 */
  /* #359: @48 = 00 */
  /* #360: @49 = 00 */
  /* #361: @59 = vertcat(@27, @28, @42, @8, @45, @46, @17, @47, @48, @49) */
  rr=w59;
  *rr++ = w42;
  *rr++ = w8;
  *rr++ = w17;
  /* #362: {NULL, NULL, @42, @8, NULL, NULL, @17, NULL, NULL, NULL} = vertsplit(@39) */
  w42 = w39[2];
  w8 = w39[3];
  w17 = w39[6];
  /* #363: @44 = (@5*@8) */
  w44  = (w5*w8);
  /* #364: @1 = (@1*@44) */
  w1 *= w44;
  /* #365: @7 = (@7*@42) */
  w7 *= w42;
  /* #366: @11 = (@11*@7) */
  w11 *= w7;
  /* #367: @1 = (@1-@11) */
  w1 -= w11;
  /* #368: @40 = (@40*@42) */
  w40 *= w42;
  /* #369: @14 = (@14*@40) */
  w14 *= w40;
  /* #370: @40 = (@4*@8) */
  w40  = (w4*w8);
  /* #371: @13 = (@13*@40) */
  w13 *= w40;
  /* #372: @14 = (@14+@13) */
  w14 += w13;
  /* #373: @1 = (@1-@14) */
  w1 -= w14;
  /* #374: @41 = (@17/@41) */
  w41  = (w17/w41);
  /* #375: @41 = (@6*@41) */
  w41  = (w6*w41);
  /* #376: @12 = (@12*@41) */
  w12 *= w41;
  /* #377: @43 = (@43*@42) */
  w43 *= w42;
  /* #378: @5 = (@5*@43) */
  w5 *= w43;
  /* #379: @12 = (@12+@5) */
  w12 += w5;
  /* #380: @0 = (@0*@42) */
  w0 *= w42;
  /* #381: @4 = (@4*@0) */
  w4 *= w0;
  /* #382: @12 = (@12-@4) */
  w12 -= w4;
  /* #383: @46 = 00 */
  /* #384: @10 = (@10*@8) */
  w10 *= w8;
  /* #385: @6 = (@6*@10) */
  w6 *= w10;
  /* #386: @6 = (@6/@18) */
  w6 /= w18;
  /* #387: @15 = (@15*@17) */
  w15 *= w17;
  /* #388: @16 = (@16*@15) */
  w16 *= w15;
  /* #389: @2 = (@2*@16) */
  w2 *= w16;
  /* #390: @6 = (@6+@2) */
  w6 += w2;
  /* #391: @47 = 00 */
  /* #392: @48 = 00 */
  /* #393: @49 = 00 */
  /* #394: @60 = vertcat(@27, @28, @1, @12, @45, @46, @6, @47, @48, @49) */
  rr=w60;
  *rr++ = w1;
  *rr++ = w12;
  *rr++ = w6;
  /* #395: @61 = horzcat(@50, @52, @53, @54, @55, @56, @57, @58, @59, @60) */
  rr=w61;
  for (i=0, cs=w50; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w54; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w56; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w57; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w58; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w60; i<3; ++i) *rr++ = *cs++;
  /* #396: @19 = mac(@26,@61,@19) */
  casadi_mtimes(w26, casadi_s2, w61, casadi_s4, w19, casadi_s3, w, 0);
  /* #397: @1 = @19[0] */
  for (rr=(&w1), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #398: output[1][0] = @1 */
  if (res[1]) res[1][0] = w1;
  /* #399: @1 = @19[1] */
  for (rr=(&w1), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #400: output[1][1] = @1 */
  if (res[1]) res[1][1] = w1;
  /* #401: @1 = @19[2] */
  for (rr=(&w1), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #402: output[1][2] = @1 */
  if (res[1]) res[1][2] = w1;
  /* #403: @1 = @19[3] */
  for (rr=(&w1), ss=w19+3; ss!=w19+4; ss+=1) *rr++ = *ss;
  /* #404: output[1][3] = @1 */
  if (res[1]) res[1][3] = w1;
  /* #405: @1 = @19[4] */
  for (rr=(&w1), ss=w19+4; ss!=w19+5; ss+=1) *rr++ = *ss;
  /* #406: output[1][4] = @1 */
  if (res[1]) res[1][4] = w1;
  /* #407: @1 = @19[5] */
  for (rr=(&w1), ss=w19+5; ss!=w19+6; ss+=1) *rr++ = *ss;
  /* #408: output[1][5] = @1 */
  if (res[1]) res[1][5] = w1;
  /* #409: @1 = @19[6] */
  for (rr=(&w1), ss=w19+6; ss!=w19+7; ss+=1) *rr++ = *ss;
  /* #410: output[1][6] = @1 */
  if (res[1]) res[1][6] = w1;
  /* #411: @1 = @19[7] */
  for (rr=(&w1), ss=w19+7; ss!=w19+8; ss+=1) *rr++ = *ss;
  /* #412: output[1][7] = @1 */
  if (res[1]) res[1][7] = w1;
  /* #413: @1 = @19[8] */
  for (rr=(&w1), ss=w19+8; ss!=w19+9; ss+=1) *rr++ = *ss;
  /* #414: output[1][8] = @1 */
  if (res[1]) res[1][8] = w1;
  /* #415: @1 = @19[9] */
  for (rr=(&w1), ss=w19+9; ss!=w19+10; ss+=1) *rr++ = *ss;
  /* #416: output[1][9] = @1 */
  if (res[1]) res[1][9] = w1;
  /* #417: @1 = @19[11] */
  for (rr=(&w1), ss=w19+11; ss!=w19+12; ss+=1) *rr++ = *ss;
  /* #418: output[1][10] = @1 */
  if (res[1]) res[1][10] = w1;
  /* #419: @1 = @19[12] */
  for (rr=(&w1), ss=w19+12; ss!=w19+13; ss+=1) *rr++ = *ss;
  /* #420: output[1][11] = @1 */
  if (res[1]) res[1][11] = w1;
  /* #421: @1 = @19[13] */
  for (rr=(&w1), ss=w19+13; ss!=w19+14; ss+=1) *rr++ = *ss;
  /* #422: output[1][12] = @1 */
  if (res[1]) res[1][12] = w1;
  /* #423: @1 = @19[14] */
  for (rr=(&w1), ss=w19+14; ss!=w19+15; ss+=1) *rr++ = *ss;
  /* #424: output[1][13] = @1 */
  if (res[1]) res[1][13] = w1;
  /* #425: @1 = @19[15] */
  for (rr=(&w1), ss=w19+15; ss!=w19+16; ss+=1) *rr++ = *ss;
  /* #426: output[1][14] = @1 */
  if (res[1]) res[1][14] = w1;
  /* #427: @1 = @19[16] */
  for (rr=(&w1), ss=w19+16; ss!=w19+17; ss+=1) *rr++ = *ss;
  /* #428: output[1][15] = @1 */
  if (res[1]) res[1][15] = w1;
  /* #429: @1 = @19[17] */
  for (rr=(&w1), ss=w19+17; ss!=w19+18; ss+=1) *rr++ = *ss;
  /* #430: output[1][16] = @1 */
  if (res[1]) res[1][16] = w1;
  /* #431: @1 = @19[18] */
  for (rr=(&w1), ss=w19+18; ss!=w19+19; ss+=1) *rr++ = *ss;
  /* #432: output[1][17] = @1 */
  if (res[1]) res[1][17] = w1;
  /* #433: @1 = @19[19] */
  for (rr=(&w1), ss=w19+19; ss!=w19+20; ss+=1) *rr++ = *ss;
  /* #434: output[1][18] = @1 */
  if (res[1]) res[1][18] = w1;
  /* #435: @1 = @19[22] */
  for (rr=(&w1), ss=w19+22; ss!=w19+23; ss+=1) *rr++ = *ss;
  /* #436: output[1][19] = @1 */
  if (res[1]) res[1][19] = w1;
  /* #437: @1 = @19[23] */
  for (rr=(&w1), ss=w19+23; ss!=w19+24; ss+=1) *rr++ = *ss;
  /* #438: output[1][20] = @1 */
  if (res[1]) res[1][20] = w1;
  /* #439: @1 = @19[24] */
  for (rr=(&w1), ss=w19+24; ss!=w19+25; ss+=1) *rr++ = *ss;
  /* #440: output[1][21] = @1 */
  if (res[1]) res[1][21] = w1;
  /* #441: @1 = @19[25] */
  for (rr=(&w1), ss=w19+25; ss!=w19+26; ss+=1) *rr++ = *ss;
  /* #442: output[1][22] = @1 */
  if (res[1]) res[1][22] = w1;
  /* #443: @1 = @19[26] */
  for (rr=(&w1), ss=w19+26; ss!=w19+27; ss+=1) *rr++ = *ss;
  /* #444: output[1][23] = @1 */
  if (res[1]) res[1][23] = w1;
  /* #445: @1 = @19[27] */
  for (rr=(&w1), ss=w19+27; ss!=w19+28; ss+=1) *rr++ = *ss;
  /* #446: output[1][24] = @1 */
  if (res[1]) res[1][24] = w1;
  /* #447: @1 = @19[28] */
  for (rr=(&w1), ss=w19+28; ss!=w19+29; ss+=1) *rr++ = *ss;
  /* #448: output[1][25] = @1 */
  if (res[1]) res[1][25] = w1;
  /* #449: @1 = @19[29] */
  for (rr=(&w1), ss=w19+29; ss!=w19+30; ss+=1) *rr++ = *ss;
  /* #450: output[1][26] = @1 */
  if (res[1]) res[1][26] = w1;
  /* #451: @1 = @19[33] */
  for (rr=(&w1), ss=w19+33; ss!=w19+34; ss+=1) *rr++ = *ss;
  /* #452: output[1][27] = @1 */
  if (res[1]) res[1][27] = w1;
  /* #453: @1 = @19[34] */
  for (rr=(&w1), ss=w19+34; ss!=w19+35; ss+=1) *rr++ = *ss;
  /* #454: output[1][28] = @1 */
  if (res[1]) res[1][28] = w1;
  /* #455: @1 = @19[35] */
  for (rr=(&w1), ss=w19+35; ss!=w19+36; ss+=1) *rr++ = *ss;
  /* #456: output[1][29] = @1 */
  if (res[1]) res[1][29] = w1;
  /* #457: @1 = @19[36] */
  for (rr=(&w1), ss=w19+36; ss!=w19+37; ss+=1) *rr++ = *ss;
  /* #458: output[1][30] = @1 */
  if (res[1]) res[1][30] = w1;
  /* #459: @1 = @19[37] */
  for (rr=(&w1), ss=w19+37; ss!=w19+38; ss+=1) *rr++ = *ss;
  /* #460: output[1][31] = @1 */
  if (res[1]) res[1][31] = w1;
  /* #461: @1 = @19[38] */
  for (rr=(&w1), ss=w19+38; ss!=w19+39; ss+=1) *rr++ = *ss;
  /* #462: output[1][32] = @1 */
  if (res[1]) res[1][32] = w1;
  /* #463: @1 = @19[39] */
  for (rr=(&w1), ss=w19+39; ss!=w19+40; ss+=1) *rr++ = *ss;
  /* #464: output[1][33] = @1 */
  if (res[1]) res[1][33] = w1;
  /* #465: @1 = @19[44] */
  for (rr=(&w1), ss=w19+44; ss!=w19+45; ss+=1) *rr++ = *ss;
  /* #466: output[1][34] = @1 */
  if (res[1]) res[1][34] = w1;
  /* #467: @1 = @19[45] */
  for (rr=(&w1), ss=w19+45; ss!=w19+46; ss+=1) *rr++ = *ss;
  /* #468: output[1][35] = @1 */
  if (res[1]) res[1][35] = w1;
  /* #469: @1 = @19[46] */
  for (rr=(&w1), ss=w19+46; ss!=w19+47; ss+=1) *rr++ = *ss;
  /* #470: output[1][36] = @1 */
  if (res[1]) res[1][36] = w1;
  /* #471: @1 = @19[47] */
  for (rr=(&w1), ss=w19+47; ss!=w19+48; ss+=1) *rr++ = *ss;
  /* #472: output[1][37] = @1 */
  if (res[1]) res[1][37] = w1;
  /* #473: @1 = @19[48] */
  for (rr=(&w1), ss=w19+48; ss!=w19+49; ss+=1) *rr++ = *ss;
  /* #474: output[1][38] = @1 */
  if (res[1]) res[1][38] = w1;
  /* #475: @1 = @19[49] */
  for (rr=(&w1), ss=w19+49; ss!=w19+50; ss+=1) *rr++ = *ss;
  /* #476: output[1][39] = @1 */
  if (res[1]) res[1][39] = w1;
  /* #477: @1 = @19[55] */
  for (rr=(&w1), ss=w19+55; ss!=w19+56; ss+=1) *rr++ = *ss;
  /* #478: output[1][40] = @1 */
  if (res[1]) res[1][40] = w1;
  /* #479: @1 = @19[56] */
  for (rr=(&w1), ss=w19+56; ss!=w19+57; ss+=1) *rr++ = *ss;
  /* #480: output[1][41] = @1 */
  if (res[1]) res[1][41] = w1;
  /* #481: @1 = @19[57] */
  for (rr=(&w1), ss=w19+57; ss!=w19+58; ss+=1) *rr++ = *ss;
  /* #482: output[1][42] = @1 */
  if (res[1]) res[1][42] = w1;
  /* #483: @1 = @19[58] */
  for (rr=(&w1), ss=w19+58; ss!=w19+59; ss+=1) *rr++ = *ss;
  /* #484: output[1][43] = @1 */
  if (res[1]) res[1][43] = w1;
  /* #485: @1 = @19[59] */
  for (rr=(&w1), ss=w19+59; ss!=w19+60; ss+=1) *rr++ = *ss;
  /* #486: output[1][44] = @1 */
  if (res[1]) res[1][44] = w1;
  /* #487: @1 = @19[66] */
  for (rr=(&w1), ss=w19+66; ss!=w19+67; ss+=1) *rr++ = *ss;
  /* #488: output[1][45] = @1 */
  if (res[1]) res[1][45] = w1;
  /* #489: @1 = @19[67] */
  for (rr=(&w1), ss=w19+67; ss!=w19+68; ss+=1) *rr++ = *ss;
  /* #490: output[1][46] = @1 */
  if (res[1]) res[1][46] = w1;
  /* #491: @1 = @19[68] */
  for (rr=(&w1), ss=w19+68; ss!=w19+69; ss+=1) *rr++ = *ss;
  /* #492: output[1][47] = @1 */
  if (res[1]) res[1][47] = w1;
  /* #493: @1 = @19[69] */
  for (rr=(&w1), ss=w19+69; ss!=w19+70; ss+=1) *rr++ = *ss;
  /* #494: output[1][48] = @1 */
  if (res[1]) res[1][48] = w1;
  /* #495: @1 = @19[77] */
  for (rr=(&w1), ss=w19+77; ss!=w19+78; ss+=1) *rr++ = *ss;
  /* #496: output[1][49] = @1 */
  if (res[1]) res[1][49] = w1;
  /* #497: @1 = @19[78] */
  for (rr=(&w1), ss=w19+78; ss!=w19+79; ss+=1) *rr++ = *ss;
  /* #498: output[1][50] = @1 */
  if (res[1]) res[1][50] = w1;
  /* #499: @1 = @19[79] */
  for (rr=(&w1), ss=w19+79; ss!=w19+80; ss+=1) *rr++ = *ss;
  /* #500: output[1][51] = @1 */
  if (res[1]) res[1][51] = w1;
  /* #501: @1 = @19[88] */
  for (rr=(&w1), ss=w19+88; ss!=w19+89; ss+=1) *rr++ = *ss;
  /* #502: output[1][52] = @1 */
  if (res[1]) res[1][52] = w1;
  /* #503: @1 = @19[89] */
  for (rr=(&w1), ss=w19+89; ss!=w19+90; ss+=1) *rr++ = *ss;
  /* #504: output[1][53] = @1 */
  if (res[1]) res[1][53] = w1;
  /* #505: @1 = @19[99] */
  for (rr=(&w1), ss=w19+99; ss!=w19+100; ss+=1) *rr++ = *ss;
  /* #506: output[1][54] = @1 */
  if (res[1]) res[1][54] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_ode_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_ode_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_ode_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_ode_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_reverse_expl_ode_hess_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_reverse_expl_ode_hess_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_bicycle_model_reverse_expl_ode_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_reverse_expl_ode_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_reverse_expl_ode_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_reverse_expl_ode_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s5;
    case 4: return casadi_s8;
    case 5: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_reverse_expl_ode_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s10;
    case 1: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 11;
  if (sz_w) *sz_w = 741;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 16*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 12*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 11*sizeof(casadi_int);
  if (sz_w) *sz_w = 741*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
