/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_bicycle_model_reverse_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[9] = {7, 3, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[13] = {3, 7, 0, 0, 0, 0, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s2[21] = {7, 3, 0, 5, 10, 15, 0, 1, 2, 3, 4, 0, 1, 2, 3, 5, 0, 1, 2, 3, 6};
static const casadi_int casadi_s3[18] = {7, 3, 0, 4, 8, 12, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s4[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s5[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s6[27] = {7, 3, 0, 7, 14, 21, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s7[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[38] = {7, 7, 0, 4, 8, 12, 16, 20, 24, 28, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};

/* f1tenth_bicycle_model_reverse_expl_vde_forw:(i0[7],i1[7x7],i2[7x3],i3[3],i4[])->(o0[7],o1[7x7,28nz],o2[7x3,15nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, *w13=w+20, *w14=w+69, *w15=w+76, *w16=w+83, *w17=w+90, *w18=w+97, *w19=w+104, *w20=w+111, w21, w22, w23, w24, w25, w26, w27, *w28=w+125, *w33=w+128, *w34=w+131, *w35=w+134, *w36=w+149, *w37=w+170, *w38=w+174, *w39=w+178, *w40=w+182, *w41=w+194;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #4: output[0][0] = @3 */
  if (res[0]) res[0][0] = w3;
  /* #5: @3 = sin(@1) */
  w3 = sin( w1 );
  /* #6: @4 = (@0*@3) */
  w4  = (w0*w3);
  /* #7: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #8: @4 = 0.331 */
  w4 = 3.3100000000000002e-01;
  /* #9: @4 = (@0/@4) */
  w4  = (w0/w4);
  /* #10: @5 = input[0][6] */
  w5 = arg[0] ? arg[0][6] : 0;
  /* #11: @6 = tan(@5) */
  w6 = tan( w5 );
  /* #12: @7 = (@4*@6) */
  w7  = (w4*w6);
  /* #13: output[0][2] = @7 */
  if (res[0]) res[0][2] = w7;
  /* #14: @7 = 0.675676 */
  w7 = 6.7567567567567566e-01;
  /* #15: @8 = 61.4282 */
  w8 = 6.1428199999999997e+01;
  /* #16: @9 = input[0][5] */
  w9 = arg[0] ? arg[0][5] : 0;
  /* #17: @9 = (@8*@9) */
  w9  = (w8*w9);
  /* #18: @10 = 3.012 */
  w10 = 3.0120000000000000e+00;
  /* #19: @11 = (@10*@0) */
  w11  = (w10*w0);
  /* #20: @9 = (@9-@11) */
  w9 -= w11;
  /* #21: @11 = 0.604 */
  w11 = 6.0399999999999998e-01;
  /* #22: @12 = sign(@0) */
  w12 = casadi_sign( w0 );
  /* #23: @11 = (@11*@12) */
  w11 *= w12;
  /* #24: @9 = (@9-@11) */
  w9 -= w11;
  /* #25: @9 = (@7*@9) */
  w9  = (w7*w9);
  /* #26: output[0][3] = @9 */
  if (res[0]) res[0][3] = w9;
  /* #27: @9 = input[3][0] */
  w9 = arg[3] ? arg[3][0] : 0;
  /* #28: output[0][4] = @9 */
  if (res[0]) res[0][4] = w9;
  /* #29: @9 = input[3][1] */
  w9 = arg[3] ? arg[3][1] : 0;
  /* #30: output[0][5] = @9 */
  if (res[0]) res[0][5] = w9;
  /* #31: @9 = input[3][2] */
  w9 = arg[3] ? arg[3][2] : 0;
  /* #32: output[0][6] = @9 */
  if (res[0]) res[0][6] = w9;
  /* #33: @13 = input[1][0] */
  casadi_copy(arg[1], 49, w13);
  /* #34: {@14, @15, @16, @17, @18, @19, @20} = horzsplit(@13) */
  casadi_copy(w13, 7, w14);
  casadi_copy(w13+7, 7, w15);
  casadi_copy(w13+14, 7, w16);
  casadi_copy(w13+21, 7, w17);
  casadi_copy(w13+28, 7, w18);
  casadi_copy(w13+35, 7, w19);
  casadi_copy(w13+42, 7, w20);
  /* #35: {NULL, NULL, @9, @11, NULL, @12, @21} = vertsplit(@14) */
  w9 = w14[2];
  w11 = w14[3];
  w12 = w14[5];
  w21 = w14[6];
  /* #36: @22 = (@2*@11) */
  w22  = (w2*w11);
  /* #37: @23 = sin(@1) */
  w23 = sin( w1 );
  /* #38: @24 = (@23*@9) */
  w24  = (w23*w9);
  /* #39: @24 = (@0*@24) */
  w24  = (w0*w24);
  /* #40: @22 = (@22-@24) */
  w22 -= w24;
  /* #41: output[1][0] = @22 */
  if (res[1]) res[1][0] = w22;
  /* #42: @22 = (@3*@11) */
  w22  = (w3*w11);
  /* #43: @24 = cos(@1) */
  w24 = cos( w1 );
  /* #44: @9 = (@24*@9) */
  w9  = (w24*w9);
  /* #45: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #46: @22 = (@22+@9) */
  w22 += w9;
  /* #47: output[1][1] = @22 */
  if (res[1]) res[1][1] = w22;
  /* #48: @22 = 3.02115 */
  w22 = 3.0211480362537761e+00;
  /* #49: @9 = (@22*@11) */
  w9  = (w22*w11);
  /* #50: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #51: @25 = cos(@5) */
  w25 = cos( w5 );
  /* #52: @25 = sq(@25) */
  w25 = casadi_sq( w25 );
  /* #53: @21 = (@21/@25) */
  w21 /= w25;
  /* #54: @21 = (@4*@21) */
  w21  = (w4*w21);
  /* #55: @9 = (@9+@21) */
  w9 += w21;
  /* #56: output[1][2] = @9 */
  if (res[1]) res[1][2] = w9;
  /* #57: @12 = (@8*@12) */
  w12  = (w8*w12);
  /* #58: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #59: @12 = (@12-@11) */
  w12 -= w11;
  /* #60: @12 = (@7*@12) */
  w12  = (w7*w12);
  /* #61: output[1][3] = @12 */
  if (res[1]) res[1][3] = w12;
  /* #62: {NULL, NULL, @12, @11, NULL, @9, @21} = vertsplit(@15) */
  w12 = w15[2];
  w11 = w15[3];
  w9 = w15[5];
  w21 = w15[6];
  /* #63: @26 = (@2*@11) */
  w26  = (w2*w11);
  /* #64: @27 = (@23*@12) */
  w27  = (w23*w12);
  /* #65: @27 = (@0*@27) */
  w27  = (w0*w27);
  /* #66: @26 = (@26-@27) */
  w26 -= w27;
  /* #67: output[1][4] = @26 */
  if (res[1]) res[1][4] = w26;
  /* #68: @26 = (@3*@11) */
  w26  = (w3*w11);
  /* #69: @12 = (@24*@12) */
  w12  = (w24*w12);
  /* #70: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #71: @26 = (@26+@12) */
  w26 += w12;
  /* #72: output[1][5] = @26 */
  if (res[1]) res[1][5] = w26;
  /* #73: @26 = (@22*@11) */
  w26  = (w22*w11);
  /* #74: @26 = (@6*@26) */
  w26  = (w6*w26);
  /* #75: @21 = (@21/@25) */
  w21 /= w25;
  /* #76: @21 = (@4*@21) */
  w21  = (w4*w21);
  /* #77: @26 = (@26+@21) */
  w26 += w21;
  /* #78: output[1][6] = @26 */
  if (res[1]) res[1][6] = w26;
  /* #79: @9 = (@8*@9) */
  w9  = (w8*w9);
  /* #80: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #81: @9 = (@9-@11) */
  w9 -= w11;
  /* #82: @9 = (@7*@9) */
  w9  = (w7*w9);
  /* #83: output[1][7] = @9 */
  if (res[1]) res[1][7] = w9;
  /* #84: {NULL, NULL, @9, @11, NULL, @26, @21} = vertsplit(@16) */
  w9 = w16[2];
  w11 = w16[3];
  w26 = w16[5];
  w21 = w16[6];
  /* #85: @12 = (@2*@11) */
  w12  = (w2*w11);
  /* #86: @27 = (@23*@9) */
  w27  = (w23*w9);
  /* #87: @27 = (@0*@27) */
  w27  = (w0*w27);
  /* #88: @12 = (@12-@27) */
  w12 -= w27;
  /* #89: output[1][8] = @12 */
  if (res[1]) res[1][8] = w12;
  /* #90: @12 = (@3*@11) */
  w12  = (w3*w11);
  /* #91: @9 = (@24*@9) */
  w9  = (w24*w9);
  /* #92: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #93: @12 = (@12+@9) */
  w12 += w9;
  /* #94: output[1][9] = @12 */
  if (res[1]) res[1][9] = w12;
  /* #95: @12 = (@22*@11) */
  w12  = (w22*w11);
  /* #96: @12 = (@6*@12) */
  w12  = (w6*w12);
  /* #97: @21 = (@21/@25) */
  w21 /= w25;
  /* #98: @21 = (@4*@21) */
  w21  = (w4*w21);
  /* #99: @12 = (@12+@21) */
  w12 += w21;
  /* #100: output[1][10] = @12 */
  if (res[1]) res[1][10] = w12;
  /* #101: @26 = (@8*@26) */
  w26  = (w8*w26);
  /* #102: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #103: @26 = (@26-@11) */
  w26 -= w11;
  /* #104: @26 = (@7*@26) */
  w26  = (w7*w26);
  /* #105: output[1][11] = @26 */
  if (res[1]) res[1][11] = w26;
  /* #106: {NULL, NULL, @26, @11, NULL, @12, @21} = vertsplit(@17) */
  w26 = w17[2];
  w11 = w17[3];
  w12 = w17[5];
  w21 = w17[6];
  /* #107: @9 = (@2*@11) */
  w9  = (w2*w11);
  /* #108: @27 = (@23*@26) */
  w27  = (w23*w26);
  /* #109: @27 = (@0*@27) */
  w27  = (w0*w27);
  /* #110: @9 = (@9-@27) */
  w9 -= w27;
  /* #111: output[1][12] = @9 */
  if (res[1]) res[1][12] = w9;
  /* #112: @9 = (@3*@11) */
  w9  = (w3*w11);
  /* #113: @26 = (@24*@26) */
  w26  = (w24*w26);
  /* #114: @26 = (@0*@26) */
  w26  = (w0*w26);
  /* #115: @9 = (@9+@26) */
  w9 += w26;
  /* #116: output[1][13] = @9 */
  if (res[1]) res[1][13] = w9;
  /* #117: @9 = (@22*@11) */
  w9  = (w22*w11);
  /* #118: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #119: @21 = (@21/@25) */
  w21 /= w25;
  /* #120: @21 = (@4*@21) */
  w21  = (w4*w21);
  /* #121: @9 = (@9+@21) */
  w9 += w21;
  /* #122: output[1][14] = @9 */
  if (res[1]) res[1][14] = w9;
  /* #123: @12 = (@8*@12) */
  w12  = (w8*w12);
  /* #124: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #125: @12 = (@12-@11) */
  w12 -= w11;
  /* #126: @12 = (@7*@12) */
  w12  = (w7*w12);
  /* #127: output[1][15] = @12 */
  if (res[1]) res[1][15] = w12;
  /* #128: {NULL, NULL, @12, @11, NULL, @9, @21} = vertsplit(@18) */
  w12 = w18[2];
  w11 = w18[3];
  w9 = w18[5];
  w21 = w18[6];
  /* #129: @26 = (@2*@11) */
  w26  = (w2*w11);
  /* #130: @27 = (@23*@12) */
  w27  = (w23*w12);
  /* #131: @27 = (@0*@27) */
  w27  = (w0*w27);
  /* #132: @26 = (@26-@27) */
  w26 -= w27;
  /* #133: output[1][16] = @26 */
  if (res[1]) res[1][16] = w26;
  /* #134: @26 = (@3*@11) */
  w26  = (w3*w11);
  /* #135: @12 = (@24*@12) */
  w12  = (w24*w12);
  /* #136: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #137: @26 = (@26+@12) */
  w26 += w12;
  /* #138: output[1][17] = @26 */
  if (res[1]) res[1][17] = w26;
  /* #139: @26 = (@22*@11) */
  w26  = (w22*w11);
  /* #140: @26 = (@6*@26) */
  w26  = (w6*w26);
  /* #141: @21 = (@21/@25) */
  w21 /= w25;
  /* #142: @21 = (@4*@21) */
  w21  = (w4*w21);
  /* #143: @26 = (@26+@21) */
  w26 += w21;
  /* #144: output[1][18] = @26 */
  if (res[1]) res[1][18] = w26;
  /* #145: @9 = (@8*@9) */
  w9  = (w8*w9);
  /* #146: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #147: @9 = (@9-@11) */
  w9 -= w11;
  /* #148: @9 = (@7*@9) */
  w9  = (w7*w9);
  /* #149: output[1][19] = @9 */
  if (res[1]) res[1][19] = w9;
  /* #150: {NULL, NULL, @9, @11, NULL, @26, @21} = vertsplit(@19) */
  w9 = w19[2];
  w11 = w19[3];
  w26 = w19[5];
  w21 = w19[6];
  /* #151: @12 = (@2*@11) */
  w12  = (w2*w11);
  /* #152: @27 = (@23*@9) */
  w27  = (w23*w9);
  /* #153: @27 = (@0*@27) */
  w27  = (w0*w27);
  /* #154: @12 = (@12-@27) */
  w12 -= w27;
  /* #155: output[1][20] = @12 */
  if (res[1]) res[1][20] = w12;
  /* #156: @12 = (@3*@11) */
  w12  = (w3*w11);
  /* #157: @9 = (@24*@9) */
  w9  = (w24*w9);
  /* #158: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #159: @12 = (@12+@9) */
  w12 += w9;
  /* #160: output[1][21] = @12 */
  if (res[1]) res[1][21] = w12;
  /* #161: @12 = (@22*@11) */
  w12  = (w22*w11);
  /* #162: @12 = (@6*@12) */
  w12  = (w6*w12);
  /* #163: @21 = (@21/@25) */
  w21 /= w25;
  /* #164: @21 = (@4*@21) */
  w21  = (w4*w21);
  /* #165: @12 = (@12+@21) */
  w12 += w21;
  /* #166: output[1][22] = @12 */
  if (res[1]) res[1][22] = w12;
  /* #167: @26 = (@8*@26) */
  w26  = (w8*w26);
  /* #168: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #169: @26 = (@26-@11) */
  w26 -= w11;
  /* #170: @26 = (@7*@26) */
  w26  = (w7*w26);
  /* #171: output[1][23] = @26 */
  if (res[1]) res[1][23] = w26;
  /* #172: {NULL, NULL, @26, @11, NULL, @12, @21} = vertsplit(@20) */
  w26 = w20[2];
  w11 = w20[3];
  w12 = w20[5];
  w21 = w20[6];
  /* #173: @9 = (@2*@11) */
  w9  = (w2*w11);
  /* #174: @23 = (@23*@26) */
  w23 *= w26;
  /* #175: @23 = (@0*@23) */
  w23  = (w0*w23);
  /* #176: @9 = (@9-@23) */
  w9 -= w23;
  /* #177: output[1][24] = @9 */
  if (res[1]) res[1][24] = w9;
  /* #178: @9 = (@3*@11) */
  w9  = (w3*w11);
  /* #179: @24 = (@24*@26) */
  w24 *= w26;
  /* #180: @24 = (@0*@24) */
  w24  = (w0*w24);
  /* #181: @9 = (@9+@24) */
  w9 += w24;
  /* #182: output[1][25] = @9 */
  if (res[1]) res[1][25] = w9;
  /* #183: @22 = (@22*@11) */
  w22 *= w11;
  /* #184: @22 = (@6*@22) */
  w22  = (w6*w22);
  /* #185: @21 = (@21/@25) */
  w21 /= w25;
  /* #186: @21 = (@4*@21) */
  w21  = (w4*w21);
  /* #187: @22 = (@22+@21) */
  w22 += w21;
  /* #188: output[1][26] = @22 */
  if (res[1]) res[1][26] = w22;
  /* #189: @12 = (@8*@12) */
  w12  = (w8*w12);
  /* #190: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #191: @12 = (@12-@11) */
  w12 -= w11;
  /* #192: @12 = (@7*@12) */
  w12  = (w7*w12);
  /* #193: output[1][27] = @12 */
  if (res[1]) res[1][27] = w12;
  /* #194: @28 = zeros(3x7,3nz) */
  casadi_clear(w28, 3);
  /* #195: @29 = 00 */
  /* #196: @30 = 00 */
  /* #197: @31 = 00 */
  /* #198: @32 = 00 */
  /* #199: @33 = ones(3x1) */
  casadi_fill(w33, 3, 1.);
  /* #200: {@12, @11, @22} = vertsplit(@33) */
  w12 = w33[0];
  w11 = w33[1];
  w22 = w33[2];
  /* #201: @33 = vertcat(@29, @30, @31, @32, @12, @11, @22) */
  rr=w33;
  *rr++ = w12;
  *rr++ = w11;
  *rr++ = w22;
  /* #202: @34 = @33[:3] */
  for (rr=w34, ss=w33+0; ss!=w33+3; ss+=1) *rr++ = *ss;
  /* #203: (@28[:3] = @34) */
  for (rr=w28+0, ss=w34; rr!=w28+3; rr+=1) *rr = *ss++;
  /* #204: @34 = @28' */
  casadi_trans(w28,casadi_s1, w34, casadi_s0, iw);
  /* #205: @35 = project(@34) */
  casadi_project(w34, casadi_s0, w35, casadi_s2, w);
  /* #206: @36 = input[2][0] */
  casadi_copy(arg[2], 21, w36);
  /* #207: {@20, @19, @18} = horzsplit(@36) */
  casadi_copy(w36, 7, w20);
  casadi_copy(w36+7, 7, w19);
  casadi_copy(w36+14, 7, w18);
  /* #208: {NULL, NULL, @12, @11, NULL, @22, @21} = vertsplit(@20) */
  w12 = w20[2];
  w11 = w20[3];
  w22 = w20[5];
  w21 = w20[6];
  /* #209: @25 = (@2*@11) */
  w25  = (w2*w11);
  /* #210: @9 = sin(@1) */
  w9 = sin( w1 );
  /* #211: @24 = (@9*@12) */
  w24  = (w9*w12);
  /* #212: @24 = (@0*@24) */
  w24  = (w0*w24);
  /* #213: @25 = (@25-@24) */
  w25 -= w24;
  /* #214: @24 = (@3*@11) */
  w24  = (w3*w11);
  /* #215: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #216: @12 = (@1*@12) */
  w12  = (w1*w12);
  /* #217: @12 = (@0*@12) */
  w12  = (w0*w12);
  /* #218: @24 = (@24+@12) */
  w24 += w12;
  /* #219: @12 = 3.02115 */
  w12 = 3.0211480362537761e+00;
  /* #220: @26 = (@12*@11) */
  w26  = (w12*w11);
  /* #221: @26 = (@6*@26) */
  w26  = (w6*w26);
  /* #222: @5 = cos(@5) */
  w5 = cos( w5 );
  /* #223: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #224: @21 = (@21/@5) */
  w21 /= w5;
  /* #225: @21 = (@4*@21) */
  w21  = (w4*w21);
  /* #226: @26 = (@26+@21) */
  w26 += w21;
  /* #227: @22 = (@8*@22) */
  w22  = (w8*w22);
  /* #228: @11 = (@10*@11) */
  w11  = (w10*w11);
  /* #229: @22 = (@22-@11) */
  w22 -= w11;
  /* #230: @22 = (@7*@22) */
  w22  = (w7*w22);
  /* #231: @29 = 00 */
  /* #232: @30 = 00 */
  /* #233: @31 = 00 */
  /* #234: @37 = vertcat(@25, @24, @26, @22, @29, @30, @31) */
  rr=w37;
  *rr++ = w25;
  *rr++ = w24;
  *rr++ = w26;
  *rr++ = w22;
  /* #235: {NULL, NULL, @25, @24, NULL, @26, @22} = vertsplit(@19) */
  w25 = w19[2];
  w24 = w19[3];
  w26 = w19[5];
  w22 = w19[6];
  /* #236: @11 = (@2*@24) */
  w11  = (w2*w24);
  /* #237: @21 = (@9*@25) */
  w21  = (w9*w25);
  /* #238: @21 = (@0*@21) */
  w21  = (w0*w21);
  /* #239: @11 = (@11-@21) */
  w11 -= w21;
  /* #240: @21 = (@3*@24) */
  w21  = (w3*w24);
  /* #241: @25 = (@1*@25) */
  w25  = (w1*w25);
  /* #242: @25 = (@0*@25) */
  w25  = (w0*w25);
  /* #243: @21 = (@21+@25) */
  w21 += w25;
  /* #244: @25 = (@12*@24) */
  w25  = (w12*w24);
  /* #245: @25 = (@6*@25) */
  w25  = (w6*w25);
  /* #246: @22 = (@22/@5) */
  w22 /= w5;
  /* #247: @22 = (@4*@22) */
  w22  = (w4*w22);
  /* #248: @25 = (@25+@22) */
  w25 += w22;
  /* #249: @26 = (@8*@26) */
  w26  = (w8*w26);
  /* #250: @24 = (@10*@24) */
  w24  = (w10*w24);
  /* #251: @26 = (@26-@24) */
  w26 -= w24;
  /* #252: @26 = (@7*@26) */
  w26  = (w7*w26);
  /* #253: @29 = 00 */
  /* #254: @30 = 00 */
  /* #255: @31 = 00 */
  /* #256: @38 = vertcat(@11, @21, @25, @26, @29, @30, @31) */
  rr=w38;
  *rr++ = w11;
  *rr++ = w21;
  *rr++ = w25;
  *rr++ = w26;
  /* #257: {NULL, NULL, @11, @21, NULL, @25, @26} = vertsplit(@18) */
  w11 = w18[2];
  w21 = w18[3];
  w25 = w18[5];
  w26 = w18[6];
  /* #258: @2 = (@2*@21) */
  w2 *= w21;
  /* #259: @9 = (@9*@11) */
  w9 *= w11;
  /* #260: @9 = (@0*@9) */
  w9  = (w0*w9);
  /* #261: @2 = (@2-@9) */
  w2 -= w9;
  /* #262: @3 = (@3*@21) */
  w3 *= w21;
  /* #263: @1 = (@1*@11) */
  w1 *= w11;
  /* #264: @0 = (@0*@1) */
  w0 *= w1;
  /* #265: @3 = (@3+@0) */
  w3 += w0;
  /* #266: @12 = (@12*@21) */
  w12 *= w21;
  /* #267: @6 = (@6*@12) */
  w6 *= w12;
  /* #268: @26 = (@26/@5) */
  w26 /= w5;
  /* #269: @4 = (@4*@26) */
  w4 *= w26;
  /* #270: @6 = (@6+@4) */
  w6 += w4;
  /* #271: @8 = (@8*@25) */
  w8 *= w25;
  /* #272: @10 = (@10*@21) */
  w10 *= w21;
  /* #273: @8 = (@8-@10) */
  w8 -= w10;
  /* #274: @7 = (@7*@8) */
  w7 *= w8;
  /* #275: @29 = 00 */
  /* #276: @30 = 00 */
  /* #277: @31 = 00 */
  /* #278: @39 = vertcat(@2, @3, @6, @7, @29, @30, @31) */
  rr=w39;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w7;
  /* #279: @40 = horzcat(@37, @38, @39) */
  rr=w40;
  for (i=0, cs=w37; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<4; ++i) *rr++ = *cs++;
  /* #280: @41 = project(@40) */
  casadi_project(w40, casadi_s3, w41, casadi_s2, w);
  /* #281: @35 = (@35+@41) */
  for (i=0, rr=w35, cs=w41; i<15; ++i) (*rr++) += (*cs++);
  /* #282: output[2][0] = @35 */
  casadi_copy(w35, 15, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_reverse_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_reverse_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_bicycle_model_reverse_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_reverse_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_reverse_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_reverse_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_reverse_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s9;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 209;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 12*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 10*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 4*sizeof(casadi_int);
  if (sz_w) *sz_w = 209*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
