/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_bicycle_model_reverse_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[11] = {10, 1, 0, 7, 2, 3, 5, 6, 7, 8, 9};

/* f1tenth_bicycle_model_reverse_expl_vde_adj:(i0[7],i1[7],i2[3],i3[])->(o0[10x1,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, *w3=w+3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 7, w3);
  /* #4: {@4, @5, @6, @7, @8, @9, @10} = vertsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  w8 = w3[4];
  w9 = w3[5];
  w10 = w3[6];
  /* #5: @11 = (@2*@5) */
  w11  = (w2*w5);
  /* #6: @1 = (@1*@11) */
  w1 *= w11;
  /* #7: @11 = sin(@0) */
  w11 = sin( w0 );
  /* #8: @12 = (@2*@4) */
  w12  = (w2*w4);
  /* #9: @11 = (@11*@12) */
  w11 *= w12;
  /* #10: @1 = (@1-@11) */
  w1 -= w11;
  /* #11: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #12: @1 = 3.02115 */
  w1 = 3.0211480362537761e+00;
  /* #13: @11 = input[0][6] */
  w11 = arg[0] ? arg[0][6] : 0;
  /* #14: @12 = tan(@11) */
  w12 = tan( w11 );
  /* #15: @12 = (@12*@6) */
  w12 *= w6;
  /* #16: @1 = (@1*@12) */
  w1 *= w12;
  /* #17: @12 = 3.012 */
  w12 = 3.0120000000000000e+00;
  /* #18: @13 = 0.675676 */
  w13 = 6.7567567567567566e-01;
  /* #19: @13 = (@13*@7) */
  w13 *= w7;
  /* #20: @12 = (@12*@13) */
  w12 *= w13;
  /* #21: @1 = (@1-@12) */
  w1 -= w12;
  /* #22: @12 = sin(@0) */
  w12 = sin( w0 );
  /* #23: @12 = (@12*@5) */
  w12 *= w5;
  /* #24: @1 = (@1+@12) */
  w1 += w12;
  /* #25: @0 = cos(@0) */
  w0 = cos( w0 );
  /* #26: @0 = (@0*@4) */
  w0 *= w4;
  /* #27: @1 = (@1+@0) */
  w1 += w0;
  /* #28: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #29: @1 = 61.4282 */
  w1 = 6.1428199999999997e+01;
  /* #30: @1 = (@1*@13) */
  w1 *= w13;
  /* #31: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #32: @1 = 0.331 */
  w1 = 3.3100000000000002e-01;
  /* #33: @2 = (@2/@1) */
  w2 /= w1;
  /* #34: @2 = (@2*@6) */
  w2 *= w6;
  /* #35: @11 = cos(@11) */
  w11 = cos( w11 );
  /* #36: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #37: @2 = (@2/@11) */
  w2 /= w11;
  /* #38: output[0][3] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #39: output[0][4] = @8 */
  if (res[0]) res[0][4] = w8;
  /* #40: output[0][5] = @9 */
  if (res[0]) res[0][5] = w9;
  /* #41: output[0][6] = @10 */
  if (res[0]) res[0][6] = w10;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_reverse_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_reverse_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_bicycle_model_reverse_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_reverse_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_reverse_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_reverse_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_reverse_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 20;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 20*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
