/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_bicycle_model_reverse_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sign CASADI_PREFIX(sign)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* f1tenth_bicycle_model_reverse_expl_ode_fun:(i0[7],i1[3],i2[])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3;
  /* #0: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #1: @1 = input[0][2] */
  w1 = arg[0] ? arg[0][2] : 0;
  /* #2: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #3: @2 = (@0*@2) */
  w2  = (w0*w2);
  /* #4: output[0][0] = @2 */
  if (res[0]) res[0][0] = w2;
  /* #5: @1 = sin(@1) */
  w1 = sin( w1 );
  /* #6: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #7: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #8: @1 = 0.331 */
  w1 = 3.3100000000000002e-01;
  /* #9: @1 = (@0/@1) */
  w1  = (w0/w1);
  /* #10: @2 = input[0][6] */
  w2 = arg[0] ? arg[0][6] : 0;
  /* #11: @2 = tan(@2) */
  w2 = tan( w2 );
  /* #12: @1 = (@1*@2) */
  w1 *= w2;
  /* #13: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  /* #14: @1 = 0.675676 */
  w1 = 6.7567567567567566e-01;
  /* #15: @2 = 61.4282 */
  w2 = 6.1428199999999997e+01;
  /* #16: @3 = input[0][5] */
  w3 = arg[0] ? arg[0][5] : 0;
  /* #17: @2 = (@2*@3) */
  w2 *= w3;
  /* #18: @3 = 3.012 */
  w3 = 3.0120000000000000e+00;
  /* #19: @3 = (@3*@0) */
  w3 *= w0;
  /* #20: @2 = (@2-@3) */
  w2 -= w3;
  /* #21: @3 = 0.604 */
  w3 = 6.0399999999999998e-01;
  /* #22: @0 = sign(@0) */
  w0 = casadi_sign( w0 );
  /* #23: @3 = (@3*@0) */
  w3 *= w0;
  /* #24: @2 = (@2-@3) */
  w2 -= w3;
  /* #25: @1 = (@1*@2) */
  w1 *= w2;
  /* #26: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #27: @1 = input[1][0] */
  w1 = arg[1] ? arg[1][0] : 0;
  /* #28: output[0][4] = @1 */
  if (res[0]) res[0][4] = w1;
  /* #29: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #30: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  /* #31: @1 = input[1][2] */
  w1 = arg[1] ? arg[1][2] : 0;
  /* #32: output[0][6] = @1 */
  if (res[0]) res[0][6] = w1;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_reverse_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_reverse_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_reverse_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_bicycle_model_reverse_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_reverse_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_reverse_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_reverse_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_reverse_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_reverse_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 4*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
