/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_bicycle_model_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[6] = {2, 1, 0, 2, 0, 1};

/* f1tenth_bicycle_model_constr_h_fun:(i0[9],i1[3],i2[],i3[])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8;
  /* #0: @0 = 61.4282 */
  w0 = 6.1428199999999997e+01;
  /* #1: @1 = input[0][7] */
  w1 = arg[0] ? arg[0][7] : 0;
  /* #2: @0 = (@0*@1) */
  w0 *= w1;
  /* #3: @1 = 3.012 */
  w1 = 3.0120000000000000e+00;
  /* #4: @2 = input[0][3] */
  w2 = arg[0] ? arg[0][3] : 0;
  /* #5: @1 = (@1*@2) */
  w1 *= w2;
  /* #6: @0 = (@0-@1) */
  w0 -= w1;
  /* #7: @1 = 0.604 */
  w1 = 6.0399999999999998e-01;
  /* #8: @3 = sign(@2) */
  w3 = casadi_sign( w2 );
  /* #9: @1 = (@1*@3) */
  w1 *= w3;
  /* #10: @0 = (@0-@1) */
  w0 -= w1;
  /* #11: @1 = sq(@0) */
  w1 = casadi_sq( w0 );
  /* #12: @3 = 100000000 */
  w3 = 100000000.;
  /* #13: @1 = (@1/@3) */
  w1 /= w3;
  /* #14: @3 = 41.7372 */
  w3 = 4.1737200000000001e+01;
  /* #15: @4 = input[0][8] */
  w4 = arg[0] ? arg[0][8] : 0;
  /* #16: @5 = input[0][4] */
  w5 = arg[0] ? arg[0][4] : 0;
  /* #17: @6 = 0.163 */
  w6 = 1.6300000000000001e-01;
  /* #18: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #19: @6 = (@6*@7) */
  w6 *= w7;
  /* #20: @6 = (@5+@6) */
  w6  = (w5+w6);
  /* #21: @8 = 0.0001 */
  w8 = 1.0000000000000000e-04;
  /* #22: @8 = (@8+@2) */
  w8 += w2;
  /* #23: @6 = atan2(@6,@8) */
  w6  = atan2(w6,w8);
  /* #24: @4 = (@4-@6) */
  w4 -= w6;
  /* #25: @3 = (@3*@4) */
  w3 *= w4;
  /* #26: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #27: @4 = 1000000 */
  w4 = 1000000.;
  /* #28: @3 = (@3/@4) */
  w3 /= w4;
  /* #29: @1 = (@1+@3) */
  w1 += w3;
  /* #30: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #31: @0 = sq(@0) */
  w0 = casadi_sq( w0 );
  /* #32: @1 = 100000000 */
  w1 = 100000000.;
  /* #33: @0 = (@0/@1) */
  w0 /= w1;
  /* #34: @1 = 29.4662 */
  w1 = 2.9466200000000001e+01;
  /* #35: @3 = 0.168 */
  w3 = 1.6800000000000001e-01;
  /* #36: @3 = (@3*@7) */
  w3 *= w7;
  /* #37: @3 = (@3-@5) */
  w3 -= w5;
  /* #38: @5 = 0.0001 */
  w5 = 1.0000000000000000e-04;
  /* #39: @5 = (@5+@2) */
  w5 += w2;
  /* #40: @3 = atan2(@3,@5) */
  w3  = atan2(w3,w5);
  /* #41: @1 = (@1*@3) */
  w1 *= w3;
  /* #42: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #43: @3 = 1000000 */
  w3 = 1000000.;
  /* #44: @1 = (@1/@3) */
  w1 /= w3;
  /* #45: @0 = (@0+@1) */
  w0 += w1;
  /* #46: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_bicycle_model_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 9;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 9*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
