/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[5] = {0, 5, 9, 13, 15};
static const casadi_int casadi_s1[4] = {1, 6, 10, 16};
static const casadi_int casadi_s2[4] = {2, 7, 11, 17};
static const casadi_int casadi_s3[4] = {4, 8, 12, 18};
static const casadi_int casadi_s4[34] = {12, 12, 0, 0, 0, 0, 0, 0, 0, 5, 9, 13, 13, 15, 19, 6, 7, 8, 10, 11, 6, 7, 8, 11, 6, 7, 8, 11, 6, 10, 6, 7, 8, 11};
static const casadi_int casadi_s5[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s6[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[14] = {12, 2, 0, 5, 9, 6, 7, 8, 10, 11, 6, 7, 8, 10};
static const casadi_int casadi_s10[3] = {2, 0, 0};

/* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess:(i0[9],i1[3],i2[2],i3[],i4[])->(o0[2],o1[12x2,9nz],o2[12x12,19nz],o3[2x0],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  const casadi_int *cii;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, *w17=w+17, w18, w19, w20, *w21=w+29, *w28=w+48, *w29=w+50, w30, w31, w32, w33, w34, w35, w36, w37, w38, w39, w40, w41, w42, w43, w44, w45, *w47=w+74, *w48=w+79, *w50=w+84, *w51=w+88, *w54=w+92, *w55=w+94;
  /* #0: @0 = 61.4282 */
  w0 = 6.1428199999999997e+01;
  /* #1: @1 = input[0][7] */
  w1 = arg[0] ? arg[0][7] : 0;
  /* #2: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #3: @2 = 3.012 */
  w2 = 3.0120000000000000e+00;
  /* #4: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #5: @4 = (@2*@3) */
  w4  = (w2*w3);
  /* #6: @1 = (@1-@4) */
  w1 -= w4;
  /* #7: @4 = 0.604 */
  w4 = 6.0399999999999998e-01;
  /* #8: @5 = (@4*@3) */
  w5  = (w4*w3);
  /* #9: @1 = (@1-@5) */
  w1 -= w5;
  /* #10: @5 = sq(@1) */
  w5 = casadi_sq( w1 );
  /* #11: @6 = 2500 */
  w6 = 2500.;
  /* #12: @5 = (@5/@6) */
  w5 /= w6;
  /* #13: @6 = 41.7372 */
  w6 = 4.1737200000000001e+01;
  /* #14: @7 = input[0][8] */
  w7 = arg[0] ? arg[0][8] : 0;
  /* #15: @8 = input[0][4] */
  w8 = arg[0] ? arg[0][4] : 0;
  /* #16: @9 = 0.163 */
  w9 = 1.6300000000000001e-01;
  /* #17: @10 = input[0][5] */
  w10 = arg[0] ? arg[0][5] : 0;
  /* #18: @11 = (@9*@10) */
  w11  = (w9*w10);
  /* #19: @11 = (@8+@11) */
  w11  = (w8+w11);
  /* #20: @12 = 0.0001 */
  w12 = 1.0000000000000000e-04;
  /* #21: @12 = (@12+@3) */
  w12 += w3;
  /* #22: @13 = atan2(@11,@12) */
  w13  = atan2(w11,w12);
  /* #23: @7 = (@7-@13) */
  w7 -= w13;
  /* #24: @7 = (@6*@7) */
  w7  = (w6*w7);
  /* #25: @13 = sq(@7) */
  w13 = casadi_sq( w7 );
  /* #26: @14 = 2500 */
  w14 = 2500.;
  /* #27: @13 = (@13/@14) */
  w13 /= w14;
  /* #28: @5 = (@5+@13) */
  w5 += w13;
  /* #29: output[0][0] = @5 */
  if (res[0]) res[0][0] = w5;
  /* #30: @5 = sq(@1) */
  w5 = casadi_sq( w1 );
  /* #31: @13 = 2500 */
  w13 = 2500.;
  /* #32: @5 = (@5/@13) */
  w5 /= w13;
  /* #33: @13 = 29.4662 */
  w13 = 2.9466200000000001e+01;
  /* #34: @14 = 0.168 */
  w14 = 1.6800000000000001e-01;
  /* #35: @10 = (@14*@10) */
  w10  = (w14*w10);
  /* #36: @10 = (@10-@8) */
  w10 -= w8;
  /* #37: @8 = 0.0001 */
  w8 = 1.0000000000000000e-04;
  /* #38: @8 = (@8+@3) */
  w8 += w3;
  /* #39: @3 = atan2(@10,@8) */
  w3  = atan2(w10,w8);
  /* #40: @3 = (@13*@3) */
  w3  = (w13*w3);
  /* #41: @15 = sq(@3) */
  w15 = casadi_sq( w3 );
  /* #42: @16 = 2500 */
  w16 = 2500.;
  /* #43: @15 = (@15/@16) */
  w15 /= w16;
  /* #44: @5 = (@5+@15) */
  w5 += w15;
  /* #45: output[0][1] = @5 */
  if (res[0]) res[0][1] = w5;
  /* #46: @17 = zeros(12x2,9nz) */
  casadi_clear(w17, 9);
  /* #47: @5 = sq(@11) */
  w5 = casadi_sq( w11 );
  /* #48: @15 = sq(@12) */
  w15 = casadi_sq( w12 );
  /* #49: @5 = (@5+@15) */
  w5 += w15;
  /* #50: @15 = (@11/@5) */
  w15  = (w11/w5);
  /* #51: @16 = (2.*@7) */
  w16 = (2.* w7 );
  /* #52: @18 = 0.0004 */
  w18 = 4.0000000000000002e-04;
  /* #53: @19 = ones(2x1,1nz) */
  w19 = 1.;
  /* #54: {@20, NULL} = vertsplit(@19) */
  w20 = w19;
  /* #55: @18 = (@18*@20) */
  w18 *= w20;
  /* #56: @16 = (@16*@18) */
  w16 *= w18;
  /* #57: @16 = (@6*@16) */
  w16  = (w6*w16);
  /* #58: @15 = (@15*@16) */
  w15 *= w16;
  /* #59: @18 = (2.*@1) */
  w18 = (2.* w1 );
  /* #60: @19 = 0.0004 */
  w19 = 4.0000000000000002e-04;
  /* #61: @19 = (@19*@20) */
  w19 *= w20;
  /* #62: @18 = (@18*@19) */
  w18 *= w19;
  /* #63: @19 = (@4*@18) */
  w19  = (w4*w18);
  /* #64: @15 = (@15-@19) */
  w15 -= w19;
  /* #65: @19 = (@2*@18) */
  w19  = (w2*w18);
  /* #66: @15 = (@15-@19) */
  w15 -= w19;
  /* #67: (@17[0] = @15) */
  for (rr=w17+0, ss=(&w15); rr!=w17+1; rr+=1) *rr = *ss++;
  /* #68: @5 = (@12/@5) */
  w5  = (w12/w5);
  /* #69: @5 = (@5*@16) */
  w5 *= w16;
  /* #70: @15 = (-@5) */
  w15 = (- w5 );
  /* #71: (@17[1] = @15) */
  for (rr=w17+1, ss=(&w15); rr!=w17+2; rr+=1) *rr = *ss++;
  /* #72: @5 = (@9*@5) */
  w5  = (w9*w5);
  /* #73: @5 = (-@5) */
  w5 = (- w5 );
  /* #74: (@17[2] = @5) */
  for (rr=w17+2, ss=(&w5); rr!=w17+3; rr+=1) *rr = *ss++;
  /* #75: @18 = (@0*@18) */
  w18  = (w0*w18);
  /* #76: (@17[3] = @18) */
  for (rr=w17+3, ss=(&w18); rr!=w17+4; rr+=1) *rr = *ss++;
  /* #77: (@17[4] = @16) */
  for (rr=w17+4, ss=(&w16); rr!=w17+5; rr+=1) *rr = *ss++;
  /* #78: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #79: @16 = 0.0004 */
  w16 = 4.0000000000000002e-04;
  /* #80: @18 = ones(2x1,1nz) */
  w18 = 1.;
  /* #81: {NULL, @5} = vertsplit(@18) */
  w5 = w18;
  /* #82: @16 = (@16*@5) */
  w16 *= w5;
  /* #83: @1 = (@1*@16) */
  w1 *= w16;
  /* #84: @16 = (@4*@1) */
  w16  = (w4*w1);
  /* #85: @16 = (-@16) */
  w16 = (- w16 );
  /* #86: @18 = sq(@10) */
  w18 = casadi_sq( w10 );
  /* #87: @15 = sq(@8) */
  w15 = casadi_sq( w8 );
  /* #88: @18 = (@18+@15) */
  w18 += w15;
  /* #89: @15 = (@10/@18) */
  w15  = (w10/w18);
  /* #90: @19 = (2.*@3) */
  w19 = (2.* w3 );
  /* #91: @20 = 0.0004 */
  w20 = 4.0000000000000002e-04;
  /* #92: @20 = (@20*@5) */
  w20 *= w5;
  /* #93: @19 = (@19*@20) */
  w19 *= w20;
  /* #94: @19 = (@13*@19) */
  w19  = (w13*w19);
  /* #95: @15 = (@15*@19) */
  w15 *= w19;
  /* #96: @16 = (@16-@15) */
  w16 -= w15;
  /* #97: @15 = (@2*@1) */
  w15  = (w2*w1);
  /* #98: @16 = (@16-@15) */
  w16 -= w15;
  /* #99: (@17[5] = @16) */
  for (rr=w17+5, ss=(&w16); rr!=w17+6; rr+=1) *rr = *ss++;
  /* #100: @18 = (@8/@18) */
  w18  = (w8/w18);
  /* #101: @18 = (@18*@19) */
  w18 *= w19;
  /* #102: @19 = (-@18) */
  w19 = (- w18 );
  /* #103: (@17[6] = @19) */
  for (rr=w17+6, ss=(&w19); rr!=w17+7; rr+=1) *rr = *ss++;
  /* #104: @18 = (@14*@18) */
  w18  = (w14*w18);
  /* #105: (@17[7] = @18) */
  for (rr=w17+7, ss=(&w18); rr!=w17+8; rr+=1) *rr = *ss++;
  /* #106: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #107: (@17[8] = @1) */
  for (rr=w17+8, ss=(&w1); rr!=w17+9; rr+=1) *rr = *ss++;
  /* #108: output[1][0] = @17 */
  casadi_copy(w17, 9, res[1]);
  /* #109: @21 = zeros(12x12,19nz) */
  casadi_clear(w21, 19);
  /* #110: @22 = 00 */
  /* #111: @23 = 00 */
  /* #112: @24 = 00 */
  /* #113: @25 = 00 */
  /* #114: @26 = 00 */
  /* #115: @27 = 00 */
  /* #116: @1 = sq(@11) */
  w1 = casadi_sq( w11 );
  /* #117: @18 = sq(@12) */
  w18 = casadi_sq( w12 );
  /* #118: @1 = (@1+@18) */
  w1 += w18;
  /* #119: @18 = (@11/@1) */
  w18  = (w11/w1);
  /* #120: @19 = 0.0004 */
  w19 = 4.0000000000000002e-04;
  /* #121: @28 = input[2][0] */
  casadi_copy(arg[2], 2, w28);
  /* #122: {@16, @15} = vertsplit(@28) */
  w16 = w28[0];
  w15 = w28[1];
  /* #123: @19 = (@19*@16) */
  w19 *= w16;
  /* #124: @20 = sq(@11) */
  w20 = casadi_sq( w11 );
  /* #125: @5 = sq(@12) */
  w5 = casadi_sq( w12 );
  /* #126: @20 = (@20+@5) */
  w20 += w5;
  /* #127: @5 = (@11/@20) */
  w5  = (w11/w20);
  /* #128: @29 = ones(12x1,8nz) */
  casadi_fill(w29, 8, 1.);
  /* #129: {NULL, NULL, NULL, NULL, NULL, NULL, @30, NULL, NULL, NULL, NULL, NULL} = vertsplit(@29) */
  w30 = w29[6];
  /* #130: @5 = (@5*@30) */
  w5 *= w30;
  /* #131: @5 = (@6*@5) */
  w5  = (w6*w5);
  /* #132: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #133: @5 = (@19*@5) */
  w5  = (w19*w5);
  /* #134: @5 = (@6*@5) */
  w5  = (w6*w5);
  /* #135: @31 = (@18*@5) */
  w31  = (w18*w5);
  /* #136: @7 = (2.*@7) */
  w7 = (2.* w7 );
  /* #137: @7 = (@7*@19) */
  w7 *= w19;
  /* #138: @7 = (@6*@7) */
  w7  = (w6*w7);
  /* #139: @32 = (@18/@1) */
  w32  = (w18/w1);
  /* #140: @33 = (2.*@12) */
  w33 = (2.* w12 );
  /* #141: @33 = (@33*@30) */
  w33 *= w30;
  /* #142: @34 = (@32*@33) */
  w34  = (w32*w33);
  /* #143: @34 = (@7*@34) */
  w34  = (w7*w34);
  /* #144: @31 = (@31-@34) */
  w31 -= w34;
  /* #145: @34 = sq(@10) */
  w34 = casadi_sq( w10 );
  /* #146: @35 = sq(@8) */
  w35 = casadi_sq( w8 );
  /* #147: @34 = (@34+@35) */
  w34 += w35;
  /* #148: @35 = (@10/@34) */
  w35  = (w10/w34);
  /* #149: @36 = 0.0004 */
  w36 = 4.0000000000000002e-04;
  /* #150: @36 = (@36*@15) */
  w36 *= w15;
  /* #151: @37 = sq(@10) */
  w37 = casadi_sq( w10 );
  /* #152: @38 = sq(@8) */
  w38 = casadi_sq( w8 );
  /* #153: @37 = (@37+@38) */
  w37 += w38;
  /* #154: @38 = (@10/@37) */
  w38  = (w10/w37);
  /* #155: @38 = (@38*@30) */
  w38 *= w30;
  /* #156: @38 = (@13*@38) */
  w38  = (w13*w38);
  /* #157: @38 = (-@38) */
  w38 = (- w38 );
  /* #158: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #159: @38 = (@36*@38) */
  w38  = (w36*w38);
  /* #160: @38 = (@13*@38) */
  w38  = (w13*w38);
  /* #161: @39 = (@35*@38) */
  w39  = (w35*w38);
  /* #162: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #163: @3 = (@3*@36) */
  w3 *= w36;
  /* #164: @3 = (@13*@3) */
  w3  = (w13*w3);
  /* #165: @40 = (@35/@34) */
  w40  = (w35/w34);
  /* #166: @41 = (2.*@8) */
  w41 = (2.* w8 );
  /* #167: @41 = (@41*@30) */
  w41 *= w30;
  /* #168: @42 = (@40*@41) */
  w42  = (w40*w41);
  /* #169: @42 = (@3*@42) */
  w42  = (w3*w42);
  /* #170: @39 = (@39-@42) */
  w39 -= w42;
  /* #171: @31 = (@31-@39) */
  w31 -= w39;
  /* #172: @39 = 0.0004 */
  w39 = 4.0000000000000002e-04;
  /* #173: @39 = (@39*@15) */
  w39 *= w15;
  /* #174: @15 = (@4*@30) */
  w15  = (w4*w30);
  /* #175: @15 = (-@15) */
  w15 = (- w15 );
  /* #176: @42 = (@2*@30) */
  w42  = (w2*w30);
  /* #177: @15 = (@15-@42) */
  w15 -= w42;
  /* #178: @42 = (2.*@15) */
  w42 = (2.* w15 );
  /* #179: @42 = (@39*@42) */
  w42  = (w39*w42);
  /* #180: @43 = 0.0004 */
  w43 = 4.0000000000000002e-04;
  /* #181: @43 = (@43*@16) */
  w43 *= w16;
  /* #182: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #183: @15 = (@43*@15) */
  w15  = (w43*w15);
  /* #184: @42 = (@42+@15) */
  w42 += w15;
  /* #185: @15 = (@4*@42) */
  w15  = (w4*w42);
  /* #186: @31 = (@31-@15) */
  w31 -= w15;
  /* #187: @15 = (@2*@42) */
  w15  = (w2*w42);
  /* #188: @31 = (@31-@15) */
  w31 -= w15;
  /* #189: @15 = (@30/@34) */
  w15  = (w30/w34);
  /* #190: @16 = (@8/@34) */
  w16  = (w8/w34);
  /* #191: @44 = (@16/@34) */
  w44  = (w16/w34);
  /* #192: @41 = (@44*@41) */
  w41  = (w44*w41);
  /* #193: @15 = (@15-@41) */
  w15 -= w41;
  /* #194: @15 = (@3*@15) */
  w15  = (w3*w15);
  /* #195: @38 = (@16*@38) */
  w38  = (w16*w38);
  /* #196: @15 = (@15+@38) */
  w15 += w38;
  /* #197: @38 = (-@15) */
  w38 = (- w15 );
  /* #198: @30 = (@30/@1) */
  w30 /= w1;
  /* #199: @41 = (@12/@1) */
  w41  = (w12/w1);
  /* #200: @45 = (@41/@1) */
  w45  = (w41/w1);
  /* #201: @33 = (@45*@33) */
  w33  = (w45*w33);
  /* #202: @30 = (@30-@33) */
  w30 -= w33;
  /* #203: @30 = (@7*@30) */
  w30  = (w7*w30);
  /* #204: @33 = (@41*@5) */
  w33  = (w41*w5);
  /* #205: @30 = (@30+@33) */
  w30 += w33;
  /* #206: @38 = (@38-@30) */
  w38 -= w30;
  /* #207: @15 = (@14*@15) */
  w15  = (w14*w15);
  /* #208: @30 = (@9*@30) */
  w30  = (w9*w30);
  /* #209: @15 = (@15-@30) */
  w15 -= w30;
  /* #210: @46 = 00 */
  /* #211: @42 = (@0*@42) */
  w42  = (w0*w42);
  /* #212: @47 = vertcat(@22, @23, @24, @25, @26, @27, @31, @38, @15, @46, @42, @5) */
  rr=w47;
  *rr++ = w31;
  *rr++ = w38;
  *rr++ = w15;
  *rr++ = w42;
  *rr++ = w5;
  /* #213: @48 = @47[:5] */
  for (rr=w48, ss=w47+0; ss!=w47+5; ss+=1) *rr++ = *ss;
  /* #214: (@21[0, 5, 9, 13, 15] = @48) */
  for (cii=casadi_s0, rr=w21, ss=w48; cii!=casadi_s0+5; ++cii, ++ss) rr[*cii] = *ss;
  /* #215: @31 = ones(12x1,1nz) */
  w31 = 1.;
  /* #216: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @38, NULL, NULL, NULL, NULL} = vertsplit(@31) */
  w38 = w31;
  /* #217: @31 = (@38/@1) */
  w31  = (w38/w1);
  /* #218: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #219: @15 = (@11*@38) */
  w15  = (w11*w38);
  /* #220: @42 = (@32*@15) */
  w42  = (w32*w15);
  /* #221: @31 = (@31-@42) */
  w31 -= w42;
  /* #222: @31 = (@7*@31) */
  w31  = (w7*w31);
  /* #223: @12 = (@12/@20) */
  w12 /= w20;
  /* #224: @20 = (@12*@38) */
  w20  = (w12*w38);
  /* #225: @20 = (@6*@20) */
  w20  = (w6*w20);
  /* #226: @20 = (-@20) */
  w20 = (- w20 );
  /* #227: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #228: @20 = (@19*@20) */
  w20  = (w19*w20);
  /* #229: @20 = (@6*@20) */
  w20  = (w6*w20);
  /* #230: @42 = (@18*@20) */
  w42  = (w18*w20);
  /* #231: @31 = (@31+@42) */
  w31 += w42;
  /* #232: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #233: @42 = (@10*@38) */
  w42  = (w10*w38);
  /* #234: @5 = (@40*@42) */
  w5  = (w40*w42);
  /* #235: @30 = (@38/@34) */
  w30  = (w38/w34);
  /* #236: @5 = (@5-@30) */
  w5 -= w30;
  /* #237: @5 = (@3*@5) */
  w5  = (w3*w5);
  /* #238: @8 = (@8/@37) */
  w8 /= w37;
  /* #239: @38 = (@8*@38) */
  w38  = (w8*w38);
  /* #240: @38 = (@13*@38) */
  w38  = (w13*w38);
  /* #241: @38 = (-@38) */
  w38 = (- w38 );
  /* #242: @38 = (2.*@38) */
  w38 = (2.* w38 );
  /* #243: @38 = (@36*@38) */
  w38  = (w36*w38);
  /* #244: @38 = (@13*@38) */
  w38  = (w13*w38);
  /* #245: @37 = (@35*@38) */
  w37  = (w35*w38);
  /* #246: @5 = (@5+@37) */
  w5 += w37;
  /* #247: @31 = (@31-@5) */
  w31 -= w5;
  /* #248: @42 = (@44*@42) */
  w42  = (w44*w42);
  /* #249: @42 = (@3*@42) */
  w42  = (w3*w42);
  /* #250: @38 = (@16*@38) */
  w38  = (w16*w38);
  /* #251: @42 = (@42+@38) */
  w42 += w38;
  /* #252: @38 = (-@42) */
  w38 = (- w42 );
  /* #253: @5 = (@41*@20) */
  w5  = (w41*w20);
  /* #254: @15 = (@45*@15) */
  w15  = (w45*w15);
  /* #255: @15 = (@7*@15) */
  w15  = (w7*w15);
  /* #256: @5 = (@5-@15) */
  w5 -= w15;
  /* #257: @38 = (@38-@5) */
  w38 -= w5;
  /* #258: @42 = (@14*@42) */
  w42  = (w14*w42);
  /* #259: @5 = (@9*@5) */
  w5  = (w9*w5);
  /* #260: @42 = (@42-@5) */
  w42 -= w5;
  /* #261: @49 = 00 */
  /* #262: @50 = vertcat(@22, @23, @24, @25, @26, @27, @31, @38, @42, @46, @49, @20) */
  rr=w50;
  *rr++ = w31;
  *rr++ = w38;
  *rr++ = w42;
  *rr++ = w20;
  /* #263: @51 = @50[:4] */
  for (rr=w51, ss=w50+0; ss!=w50+4; ss+=1) *rr++ = *ss;
  /* #264: (@21[1, 6, 10, 16] = @51) */
  for (cii=casadi_s1, rr=w21, ss=w51; cii!=casadi_s1+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #265: @31 = ones(12x1,1nz) */
  w31 = 1.;
  /* #266: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @38, NULL, NULL, NULL} = vertsplit(@31) */
  w38 = w31;
  /* #267: @31 = (@9*@38) */
  w31  = (w9*w38);
  /* #268: @1 = (@31/@1) */
  w1  = (w31/w1);
  /* #269: @11 = (@11*@31) */
  w11 *= w31;
  /* #270: @32 = (@32*@11) */
  w32 *= w11;
  /* #271: @1 = (@1-@32) */
  w1 -= w32;
  /* #272: @1 = (@7*@1) */
  w1  = (w7*w1);
  /* #273: @12 = (@12*@31) */
  w12 *= w31;
  /* #274: @12 = (@6*@12) */
  w12  = (w6*w12);
  /* #275: @12 = (-@12) */
  w12 = (- w12 );
  /* #276: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #277: @12 = (@19*@12) */
  w12  = (w19*w12);
  /* #278: @12 = (@6*@12) */
  w12  = (w6*w12);
  /* #279: @31 = (@18*@12) */
  w31  = (w18*w12);
  /* #280: @1 = (@1+@31) */
  w1 += w31;
  /* #281: @38 = (@14*@38) */
  w38  = (w14*w38);
  /* #282: @34 = (@38/@34) */
  w34  = (w38/w34);
  /* #283: @10 = (@10*@38) */
  w10 *= w38;
  /* #284: @40 = (@40*@10) */
  w40 *= w10;
  /* #285: @34 = (@34-@40) */
  w34 -= w40;
  /* #286: @34 = (@3*@34) */
  w34  = (w3*w34);
  /* #287: @8 = (@8*@38) */
  w8 *= w38;
  /* #288: @8 = (@13*@8) */
  w8  = (w13*w8);
  /* #289: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #290: @36 = (@36*@8) */
  w36 *= w8;
  /* #291: @13 = (@13*@36) */
  w13 *= w36;
  /* #292: @35 = (@35*@13) */
  w35 *= w13;
  /* #293: @34 = (@34+@35) */
  w34 += w35;
  /* #294: @1 = (@1-@34) */
  w1 -= w34;
  /* #295: @16 = (@16*@13) */
  w16 *= w13;
  /* #296: @44 = (@44*@10) */
  w44 *= w10;
  /* #297: @3 = (@3*@44) */
  w3 *= w44;
  /* #298: @16 = (@16-@3) */
  w16 -= w3;
  /* #299: @3 = (-@16) */
  w3 = (- w16 );
  /* #300: @44 = (@41*@12) */
  w44  = (w41*w12);
  /* #301: @45 = (@45*@11) */
  w45 *= w11;
  /* #302: @7 = (@7*@45) */
  w7 *= w45;
  /* #303: @44 = (@44-@7) */
  w44 -= w7;
  /* #304: @3 = (@3-@44) */
  w3 -= w44;
  /* #305: @14 = (@14*@16) */
  w14 *= w16;
  /* #306: @44 = (@9*@44) */
  w44  = (w9*w44);
  /* #307: @14 = (@14-@44) */
  w14 -= w44;
  /* #308: @49 = 00 */
  /* #309: @51 = vertcat(@22, @23, @24, @25, @26, @27, @1, @3, @14, @46, @49, @12) */
  rr=w51;
  *rr++ = w1;
  *rr++ = w3;
  *rr++ = w14;
  *rr++ = w12;
  /* #310: @50 = @51[:4] */
  for (rr=w50, ss=w51+0; ss!=w51+4; ss+=1) *rr++ = *ss;
  /* #311: (@21[2, 7, 11, 17] = @50) */
  for (cii=casadi_s2, rr=w21, ss=w50; cii!=casadi_s2+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #312: @1 = ones(12x1,1nz) */
  w1 = 1.;
  /* #313: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @3, NULL} = vertsplit(@1) */
  w3 = w1;
  /* #314: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #315: @1 = (2.*@3) */
  w1 = (2.* w3 );
  /* #316: @39 = (@39*@1) */
  w39 *= w1;
  /* #317: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #318: @43 = (@43*@3) */
  w43 *= w3;
  /* #319: @39 = (@39+@43) */
  w39 += w43;
  /* #320: @2 = (@2*@39) */
  w2 *= w39;
  /* #321: @2 = (-@2) */
  w2 = (- w2 );
  /* #322: @4 = (@4*@39) */
  w4 *= w39;
  /* #323: @2 = (@2-@4) */
  w2 -= w4;
  /* #324: @49 = 00 */
  /* #325: @52 = 00 */
  /* #326: @0 = (@0*@39) */
  w0 *= w39;
  /* #327: @53 = 00 */
  /* #328: @28 = vertcat(@22, @23, @24, @25, @26, @27, @2, @49, @52, @46, @0, @53) */
  rr=w28;
  *rr++ = w2;
  *rr++ = w0;
  /* #329: @54 = @28[:2] */
  for (rr=w54, ss=w28+0; ss!=w28+2; ss+=1) *rr++ = *ss;
  /* #330: (@21[3:25:11] = @54) */
  for (rr=w21+3, ss=w54; rr!=w21+25; rr+=11) *rr = *ss++;
  /* #331: @2 = ones(12x1,1nz) */
  w2 = 1.;
  /* #332: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @0} = vertsplit(@2) */
  w0 = w2;
  /* #333: @0 = (@6*@0) */
  w0  = (w6*w0);
  /* #334: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #335: @19 = (@19*@0) */
  w19 *= w0;
  /* #336: @6 = (@6*@19) */
  w6 *= w19;
  /* #337: @18 = (@18*@6) */
  w18 *= w6;
  /* #338: @41 = (@41*@6) */
  w41 *= w6;
  /* #339: @19 = (-@41) */
  w19 = (- w41 );
  /* #340: @9 = (@9*@41) */
  w9 *= w41;
  /* #341: @9 = (-@9) */
  w9 = (- w9 );
  /* #342: @49 = 00 */
  /* #343: @50 = vertcat(@22, @23, @24, @25, @26, @27, @18, @19, @9, @46, @49, @6) */
  rr=w50;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w9;
  *rr++ = w6;
  /* #344: @51 = @50[:4] */
  for (rr=w51, ss=w50+0; ss!=w50+4; ss+=1) *rr++ = *ss;
  /* #345: (@21[4, 8, 12, 18] = @51) */
  for (cii=casadi_s3, rr=w21, ss=w51; cii!=casadi_s3+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #346: @55 = @21' */
  casadi_trans(w21,casadi_s4, w55, casadi_s4, iw);
  /* #347: output[2][0] = @55 */
  casadi_copy(w55, 19, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s9;
    case 2: return casadi_s4;
    case 3: return casadi_s10;
    case 4: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 13;
  if (sz_w) *sz_w = 113;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 17*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 13*sizeof(casadi_int);
  if (sz_w) *sz_w = 113*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
