/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[8] = {12, 1, 0, 4, 6, 7, 8, 10};
static const casadi_int casadi_s5[3] = {1, 0, 0};

/* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt:(i0[9],i1[3],i2[],i3[])->(o0,o1[12x1,4nz],o2[1x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, *w12=w+12;
  /* #0: @0 = 52.4282 */
  w0 = 5.2428199999999997e+01;
  /* #1: @1 = input[0][7] */
  w1 = arg[0] ? arg[0][7] : 0;
  /* #2: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #3: @2 = 5.2465 */
  w2 = 5.2465000000000002e+00;
  /* #4: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #5: @4 = (@2*@3) */
  w4  = (w2*w3);
  /* #6: @1 = (@1-@4) */
  w1 -= w4;
  /* #7: @4 = 1.1194 */
  w4 = 1.1194000000000000e+00;
  /* #8: @5 = (@4*@3) */
  w5  = (w4*w3);
  /* #9: @1 = (@1-@5) */
  w1 -= w5;
  /* #10: @5 = sq(@1) */
  w5 = casadi_sq( w1 );
  /* #11: @6 = 1000 */
  w6 = 1000.;
  /* #12: @5 = (@5/@6) */
  w5 /= w6;
  /* #13: @6 = 29.4662 */
  w6 = 2.9466200000000001e+01;
  /* #14: @7 = 0.168 */
  w7 = 1.6800000000000001e-01;
  /* #15: @8 = input[0][5] */
  w8 = arg[0] ? arg[0][5] : 0;
  /* #16: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #17: @9 = input[0][4] */
  w9 = arg[0] ? arg[0][4] : 0;
  /* #18: @8 = (@8-@9) */
  w8 -= w9;
  /* #19: @9 = 0.0001 */
  w9 = 1.0000000000000000e-04;
  /* #20: @9 = (@9+@3) */
  w9 += w3;
  /* #21: @3 = atan2(@8,@9) */
  w3  = atan2(w8,w9);
  /* #22: @3 = (@6*@3) */
  w3  = (w6*w3);
  /* #23: @10 = sq(@3) */
  w10 = casadi_sq( w3 );
  /* #24: @11 = 10 */
  w11 = 10.;
  /* #25: @10 = (@10/@11) */
  w10 /= w11;
  /* #26: @5 = (@5+@10) */
  w5 += w10;
  /* #27: output[0][0] = @5 */
  if (res[0]) res[0][0] = w5;
  /* #28: @12 = zeros(12x1,4nz) */
  casadi_clear(w12, 4);
  /* #29: @5 = 0.001 */
  w5 = 1.0000000000000000e-03;
  /* #30: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #31: @5 = (@5*@1) */
  w5 *= w1;
  /* #32: @4 = (@4*@5) */
  w4 *= w5;
  /* #33: @4 = (-@4) */
  w4 = (- w4 );
  /* #34: @1 = sq(@8) */
  w1 = casadi_sq( w8 );
  /* #35: @10 = sq(@9) */
  w10 = casadi_sq( w9 );
  /* #36: @1 = (@1+@10) */
  w1 += w10;
  /* #37: @8 = (@8/@1) */
  w8 /= w1;
  /* #38: @10 = 0.1 */
  w10 = 1.0000000000000001e-01;
  /* #39: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #40: @10 = (@10*@3) */
  w10 *= w3;
  /* #41: @6 = (@6*@10) */
  w6 *= w10;
  /* #42: @8 = (@8*@6) */
  w8 *= w6;
  /* #43: @4 = (@4-@8) */
  w4 -= w8;
  /* #44: @2 = (@2*@5) */
  w2 *= w5;
  /* #45: @4 = (@4-@2) */
  w4 -= w2;
  /* #46: (@12[0] = @4) */
  for (rr=w12+0, ss=(&w4); rr!=w12+1; rr+=1) *rr = *ss++;
  /* #47: @9 = (@9/@1) */
  w9 /= w1;
  /* #48: @9 = (@9*@6) */
  w9 *= w6;
  /* #49: @6 = (-@9) */
  w6 = (- w9 );
  /* #50: (@12[1] = @6) */
  for (rr=w12+1, ss=(&w6); rr!=w12+2; rr+=1) *rr = *ss++;
  /* #51: @7 = (@7*@9) */
  w7 *= w9;
  /* #52: (@12[2] = @7) */
  for (rr=w12+2, ss=(&w7); rr!=w12+3; rr+=1) *rr = *ss++;
  /* #53: @0 = (@0*@5) */
  w0 *= w5;
  /* #54: (@12[3] = @0) */
  for (rr=w12+3, ss=(&w0); rr!=w12+4; rr+=1) *rr = *ss++;
  /* #55: output[1][0] = @12 */
  casadi_copy(w12, 4, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 16;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 16*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
