/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[4] = {0, 4, 7, 10};
static const casadi_int casadi_s1[3] = {1, 5, 8};
static const casadi_int casadi_s2[3] = {2, 6, 9};
static const casadi_int casadi_s3[27] = {12, 12, 0, 0, 0, 0, 0, 0, 0, 4, 7, 10, 10, 12, 12, 6, 7, 8, 10, 6, 7, 8, 6, 7, 8, 6, 10};
static const casadi_int casadi_s4[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s5[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s6[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[8] = {12, 1, 0, 4, 6, 7, 8, 10};
static const casadi_int casadi_s9[3] = {1, 0, 0};

/* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess:(i0[9],i1[3],i2,i3[],i4[])->(o0,o1[12x1,4nz],o2[12x12,12nz],o3[1x0],o4[]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  const casadi_int *cii;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, *w12=w+12, w13, w14, *w15=w+18, *w22=w+30, w23, w24, w25, w26, w27, w28, w29, *w32=w+46, *w34=w+50, *w35=w+53, *w37=w+56, *w38=w+58, *w39=w+60;
  /* #0: @0 = 52.4282 */
  w0 = 5.2428199999999997e+01;
  /* #1: @1 = input[0][7] */
  w1 = arg[0] ? arg[0][7] : 0;
  /* #2: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #3: @2 = 5.2465 */
  w2 = 5.2465000000000002e+00;
  /* #4: @3 = input[0][3] */
  w3 = arg[0] ? arg[0][3] : 0;
  /* #5: @4 = (@2*@3) */
  w4  = (w2*w3);
  /* #6: @1 = (@1-@4) */
  w1 -= w4;
  /* #7: @4 = 1.1194 */
  w4 = 1.1194000000000000e+00;
  /* #8: @5 = (@4*@3) */
  w5  = (w4*w3);
  /* #9: @1 = (@1-@5) */
  w1 -= w5;
  /* #10: @5 = sq(@1) */
  w5 = casadi_sq( w1 );
  /* #11: @6 = 1000 */
  w6 = 1000.;
  /* #12: @5 = (@5/@6) */
  w5 /= w6;
  /* #13: @6 = 29.4662 */
  w6 = 2.9466200000000001e+01;
  /* #14: @7 = 0.168 */
  w7 = 1.6800000000000001e-01;
  /* #15: @8 = input[0][5] */
  w8 = arg[0] ? arg[0][5] : 0;
  /* #16: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #17: @9 = input[0][4] */
  w9 = arg[0] ? arg[0][4] : 0;
  /* #18: @8 = (@8-@9) */
  w8 -= w9;
  /* #19: @9 = 0.0001 */
  w9 = 1.0000000000000000e-04;
  /* #20: @9 = (@9+@3) */
  w9 += w3;
  /* #21: @3 = atan2(@8,@9) */
  w3  = atan2(w8,w9);
  /* #22: @3 = (@6*@3) */
  w3  = (w6*w3);
  /* #23: @10 = sq(@3) */
  w10 = casadi_sq( w3 );
  /* #24: @11 = 10 */
  w11 = 10.;
  /* #25: @10 = (@10/@11) */
  w10 /= w11;
  /* #26: @5 = (@5+@10) */
  w5 += w10;
  /* #27: output[0][0] = @5 */
  if (res[0]) res[0][0] = w5;
  /* #28: @12 = zeros(12x1,4nz) */
  casadi_clear(w12, 4);
  /* #29: @5 = 0.001 */
  w5 = 1.0000000000000000e-03;
  /* #30: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #31: @5 = (@5*@1) */
  w5 *= w1;
  /* #32: @1 = (@4*@5) */
  w1  = (w4*w5);
  /* #33: @1 = (-@1) */
  w1 = (- w1 );
  /* #34: @10 = sq(@8) */
  w10 = casadi_sq( w8 );
  /* #35: @11 = sq(@9) */
  w11 = casadi_sq( w9 );
  /* #36: @10 = (@10+@11) */
  w10 += w11;
  /* #37: @11 = (@8/@10) */
  w11  = (w8/w10);
  /* #38: @13 = 0.1 */
  w13 = 1.0000000000000001e-01;
  /* #39: @14 = (2.*@3) */
  w14 = (2.* w3 );
  /* #40: @13 = (@13*@14) */
  w13 *= w14;
  /* #41: @13 = (@6*@13) */
  w13  = (w6*w13);
  /* #42: @11 = (@11*@13) */
  w11 *= w13;
  /* #43: @1 = (@1-@11) */
  w1 -= w11;
  /* #44: @11 = (@2*@5) */
  w11  = (w2*w5);
  /* #45: @1 = (@1-@11) */
  w1 -= w11;
  /* #46: (@12[0] = @1) */
  for (rr=w12+0, ss=(&w1); rr!=w12+1; rr+=1) *rr = *ss++;
  /* #47: @10 = (@9/@10) */
  w10  = (w9/w10);
  /* #48: @10 = (@10*@13) */
  w10 *= w13;
  /* #49: @13 = (-@10) */
  w13 = (- w10 );
  /* #50: (@12[1] = @13) */
  for (rr=w12+1, ss=(&w13); rr!=w12+2; rr+=1) *rr = *ss++;
  /* #51: @10 = (@7*@10) */
  w10  = (w7*w10);
  /* #52: (@12[2] = @10) */
  for (rr=w12+2, ss=(&w10); rr!=w12+3; rr+=1) *rr = *ss++;
  /* #53: @5 = (@0*@5) */
  w5  = (w0*w5);
  /* #54: (@12[3] = @5) */
  for (rr=w12+3, ss=(&w5); rr!=w12+4; rr+=1) *rr = *ss++;
  /* #55: output[1][0] = @12 */
  casadi_copy(w12, 4, res[1]);
  /* #56: @15 = zeros(12x12,12nz) */
  casadi_clear(w15, 12);
  /* #57: @16 = 00 */
  /* #58: @17 = 00 */
  /* #59: @18 = 00 */
  /* #60: @19 = 00 */
  /* #61: @20 = 00 */
  /* #62: @21 = 00 */
  /* #63: @5 = sq(@8) */
  w5 = casadi_sq( w8 );
  /* #64: @10 = sq(@9) */
  w10 = casadi_sq( w9 );
  /* #65: @5 = (@5+@10) */
  w5 += w10;
  /* #66: @10 = (@8/@5) */
  w10  = (w8/w5);
  /* #67: @13 = 0.1 */
  w13 = 1.0000000000000001e-01;
  /* #68: @1 = input[2][0] */
  w1 = arg[2] ? arg[2][0] : 0;
  /* #69: @13 = (@13*@1) */
  w13 *= w1;
  /* #70: @11 = sq(@8) */
  w11 = casadi_sq( w8 );
  /* #71: @14 = sq(@9) */
  w14 = casadi_sq( w9 );
  /* #72: @11 = (@11+@14) */
  w11 += w14;
  /* #73: @14 = (@8/@11) */
  w14  = (w8/w11);
  /* #74: @22 = ones(12x1,9nz) */
  casadi_fill(w22, 9, 1.);
  /* #75: {NULL, NULL, NULL, NULL, NULL, NULL, @23, NULL, NULL, NULL, NULL, NULL} = vertsplit(@22) */
  w23 = w22[6];
  /* #76: @14 = (@14*@23) */
  w14 *= w23;
  /* #77: @14 = (@6*@14) */
  w14  = (w6*w14);
  /* #78: @14 = (-@14) */
  w14 = (- w14 );
  /* #79: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #80: @14 = (@13*@14) */
  w14  = (w13*w14);
  /* #81: @14 = (@6*@14) */
  w14  = (w6*w14);
  /* #82: @24 = (@10*@14) */
  w24  = (w10*w14);
  /* #83: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #84: @3 = (@3*@13) */
  w3 *= w13;
  /* #85: @3 = (@6*@3) */
  w3  = (w6*w3);
  /* #86: @25 = (@10/@5) */
  w25  = (w10/w5);
  /* #87: @26 = (2.*@9) */
  w26 = (2.* w9 );
  /* #88: @26 = (@26*@23) */
  w26 *= w23;
  /* #89: @27 = (@25*@26) */
  w27  = (w25*w26);
  /* #90: @27 = (@3*@27) */
  w27  = (w3*w27);
  /* #91: @24 = (@24-@27) */
  w24 -= w27;
  /* #92: @24 = (-@24) */
  w24 = (- w24 );
  /* #93: @27 = 0.001 */
  w27 = 1.0000000000000000e-03;
  /* #94: @27 = (@27*@1) */
  w27 *= w1;
  /* #95: @1 = (@4*@23) */
  w1  = (w4*w23);
  /* #96: @1 = (-@1) */
  w1 = (- w1 );
  /* #97: @28 = (@2*@23) */
  w28  = (w2*w23);
  /* #98: @1 = (@1-@28) */
  w1 -= w28;
  /* #99: @1 = (2.*@1) */
  w1 = (2.* w1 );
  /* #100: @1 = (@27*@1) */
  w1  = (w27*w1);
  /* #101: @28 = (@4*@1) */
  w28  = (w4*w1);
  /* #102: @24 = (@24-@28) */
  w24 -= w28;
  /* #103: @28 = (@2*@1) */
  w28  = (w2*w1);
  /* #104: @24 = (@24-@28) */
  w24 -= w28;
  /* #105: @23 = (@23/@5) */
  w23 /= w5;
  /* #106: @28 = (@9/@5) */
  w28  = (w9/w5);
  /* #107: @29 = (@28/@5) */
  w29  = (w28/w5);
  /* #108: @26 = (@29*@26) */
  w26  = (w29*w26);
  /* #109: @23 = (@23-@26) */
  w23 -= w26;
  /* #110: @23 = (@3*@23) */
  w23  = (w3*w23);
  /* #111: @14 = (@28*@14) */
  w14  = (w28*w14);
  /* #112: @23 = (@23+@14) */
  w23 += w14;
  /* #113: @14 = (-@23) */
  w14 = (- w23 );
  /* #114: @23 = (@7*@23) */
  w23  = (w7*w23);
  /* #115: @30 = 00 */
  /* #116: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #117: @31 = 00 */
  /* #118: @12 = vertcat(@16, @17, @18, @19, @20, @21, @24, @14, @23, @30, @1, @31) */
  rr=w12;
  *rr++ = w24;
  *rr++ = w14;
  *rr++ = w23;
  *rr++ = w1;
  /* #119: @32 = @12[:4] */
  for (rr=w32, ss=w12+0; ss!=w12+4; ss+=1) *rr++ = *ss;
  /* #120: (@15[0, 4, 7, 10] = @32) */
  for (cii=casadi_s0, rr=w15, ss=w32; cii!=casadi_s0+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #121: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #122: @24 = ones(12x1,1nz) */
  w24 = 1.;
  /* #123: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @14, NULL, NULL, NULL, NULL} = vertsplit(@24) */
  w14 = w24;
  /* #124: @24 = (@8*@14) */
  w24  = (w8*w14);
  /* #125: @23 = (@25*@24) */
  w23  = (w25*w24);
  /* #126: @1 = (@14/@5) */
  w1  = (w14/w5);
  /* #127: @23 = (@23-@1) */
  w23 -= w1;
  /* #128: @23 = (@3*@23) */
  w23  = (w3*w23);
  /* #129: @9 = (@9/@11) */
  w9 /= w11;
  /* #130: @14 = (@9*@14) */
  w14  = (w9*w14);
  /* #131: @14 = (@6*@14) */
  w14  = (w6*w14);
  /* #132: @14 = (-@14) */
  w14 = (- w14 );
  /* #133: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #134: @14 = (@13*@14) */
  w14  = (w13*w14);
  /* #135: @14 = (@6*@14) */
  w14  = (w6*w14);
  /* #136: @11 = (@10*@14) */
  w11  = (w10*w14);
  /* #137: @23 = (@23+@11) */
  w23 += w11;
  /* #138: @23 = (-@23) */
  w23 = (- w23 );
  /* #139: @24 = (@29*@24) */
  w24  = (w29*w24);
  /* #140: @24 = (@3*@24) */
  w24  = (w3*w24);
  /* #141: @14 = (@28*@14) */
  w14  = (w28*w14);
  /* #142: @24 = (@24+@14) */
  w24 += w14;
  /* #143: @14 = (-@24) */
  w14 = (- w24 );
  /* #144: @24 = (@7*@24) */
  w24  = (w7*w24);
  /* #145: @33 = 00 */
  /* #146: @34 = vertcat(@16, @17, @18, @19, @20, @21, @23, @14, @24, @30, @33, @31) */
  rr=w34;
  *rr++ = w23;
  *rr++ = w14;
  *rr++ = w24;
  /* #147: @35 = @34[:3] */
  for (rr=w35, ss=w34+0; ss!=w34+3; ss+=1) *rr++ = *ss;
  /* #148: (@15[1, 5, 8] = @35) */
  for (cii=casadi_s1, rr=w15, ss=w35; cii!=casadi_s1+3; ++cii, ++ss) rr[*cii] = *ss;
  /* #149: @23 = ones(12x1,1nz) */
  w23 = 1.;
  /* #150: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @14, NULL, NULL, NULL} = vertsplit(@23) */
  w14 = w23;
  /* #151: @14 = (@7*@14) */
  w14  = (w7*w14);
  /* #152: @5 = (@14/@5) */
  w5  = (w14/w5);
  /* #153: @8 = (@8*@14) */
  w8 *= w14;
  /* #154: @25 = (@25*@8) */
  w25 *= w8;
  /* #155: @5 = (@5-@25) */
  w5 -= w25;
  /* #156: @5 = (@3*@5) */
  w5  = (w3*w5);
  /* #157: @9 = (@9*@14) */
  w9 *= w14;
  /* #158: @9 = (@6*@9) */
  w9  = (w6*w9);
  /* #159: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #160: @13 = (@13*@9) */
  w13 *= w9;
  /* #161: @6 = (@6*@13) */
  w6 *= w13;
  /* #162: @10 = (@10*@6) */
  w10 *= w6;
  /* #163: @5 = (@5+@10) */
  w5 += w10;
  /* #164: @5 = (-@5) */
  w5 = (- w5 );
  /* #165: @28 = (@28*@6) */
  w28 *= w6;
  /* #166: @29 = (@29*@8) */
  w29 *= w8;
  /* #167: @3 = (@3*@29) */
  w3 *= w29;
  /* #168: @28 = (@28-@3) */
  w28 -= w3;
  /* #169: @3 = (-@28) */
  w3 = (- w28 );
  /* #170: @7 = (@7*@28) */
  w7 *= w28;
  /* #171: @33 = 00 */
  /* #172: @35 = vertcat(@16, @17, @18, @19, @20, @21, @5, @3, @7, @30, @33, @31) */
  rr=w35;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w7;
  /* #173: @34 = @35[:3] */
  for (rr=w34, ss=w35+0; ss!=w35+3; ss+=1) *rr++ = *ss;
  /* #174: (@15[2, 6, 9] = @34) */
  for (cii=casadi_s2, rr=w15, ss=w34; cii!=casadi_s2+3; ++cii, ++ss) rr[*cii] = *ss;
  /* #175: @5 = ones(12x1,1nz) */
  w5 = 1.;
  /* #176: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @3, NULL} = vertsplit(@5) */
  w3 = w5;
  /* #177: @3 = (@0*@3) */
  w3  = (w0*w3);
  /* #178: @3 = (2.*@3) */
  w3 = (2.* w3 );
  /* #179: @27 = (@27*@3) */
  w27 *= w3;
  /* #180: @2 = (@2*@27) */
  w2 *= w27;
  /* #181: @2 = (-@2) */
  w2 = (- w2 );
  /* #182: @4 = (@4*@27) */
  w4 *= w27;
  /* #183: @2 = (@2-@4) */
  w2 -= w4;
  /* #184: @33 = 00 */
  /* #185: @36 = 00 */
  /* #186: @0 = (@0*@27) */
  w0 *= w27;
  /* #187: @37 = vertcat(@16, @17, @18, @19, @20, @21, @2, @33, @36, @30, @0, @31) */
  rr=w37;
  *rr++ = w2;
  *rr++ = w0;
  /* #188: @38 = @37[:2] */
  for (rr=w38, ss=w37+0; ss!=w37+2; ss+=1) *rr++ = *ss;
  /* #189: (@15[3:19:8] = @38) */
  for (rr=w15+3, ss=w38; rr!=w15+19; rr+=8) *rr = *ss++;
  /* #190: @39 = @15' */
  casadi_trans(w15,casadi_s3, w39, casadi_s3, iw);
  /* #191: output[2][0] = @39 */
  casadi_copy(w39, 12, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s8;
    case 2: return casadi_s3;
    case 3: return casadi_s9;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17;
  if (sz_res) *sz_res = 17;
  if (sz_iw) *sz_iw = 13;
  if (sz_w) *sz_w = 72;
  return 0;
}

CASADI_SYMBOL_EXPORT int f1tenth_bicycle_model_constr_h_fun_jac_uxt_zt_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 17*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 17*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 13*sizeof(casadi_int);
  if (sz_w) *sz_w = 72*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
